Update to Webinoly 1.14.1

diff --git a/assets/webinoly/lib/general b/assets/webinoly/lib/general
--- a/assets/webinoly/lib/general
+++ b/assets/webinoly/lib/general
@@ -4,7 +4,7 @@
 # Prevent 'tput' errors when running from Cron
 [[ -z $TERM || $TERM == "unknown" || $TERM == "dumb" ]] && export TERM=dumb
 
-readonly app_version="1.14.0"
+readonly app_version="1.14.1"
 readonly svr_version="1.6"
 readonly os_ubuntu_supported=(bionic focal)
 readonly php_supported=(7.2 7.3 7.4 8.0)
@@ -59,8 +59,8 @@ conf_write() {
 # ***********************************************
 # Useful variables   ****************************
 # ***********************************************
-readonly ADMIN_PASS=$( echo $(conf_read mysql-admin) | openssl enc -d -a -salt )
-
+ADMIN_PASS=$( echo $(conf_read mysql-admin) | openssl enc -d -a -salt )
+[[ -z $ADMIN_PASS ]] && readonly ADMIN_PASS="dUmb" || readonly ADMIN_PASS=$ADMIN_PASS # Never empty, prevent asking password!
 
 
 
@@ -180,8 +180,11 @@ check_for_mysql_client() {
 
 
 check_mysql_connection() {
-	if [[ -n $1 && -n $2 && -n $3 && -n $4 && $(conf_read mysql-client) == "true"  ]]; then
-		sudo mysql --connect-timeout=10 -h "$1" -P "$2" -u"$3" -p"$4" -e "quit"
+	local query="quit"
+
+	if [[ -n $1 && ${1,,} != "localhost" && -n $2 && -n $3 && -n $4 && $(conf_read mysql-client) == "true"  ]]; then
+		[[ -n $5 ]] && local query="use $5"
+		sudo mysql --connect-timeout=10 -h "$1" -P "$2" -u"$3" -p"$4" -e "$query"
 		if [[ $? != "0" ]]; then
 			echo "${red}============================================" >&2
 			echo "    [Error]  Database conection failed." >&2
@@ -196,12 +199,13 @@ check_mysql_connection() {
 		if [[ -n $2 && -n $3 ]]; then
 			local dbu=$2
 			local dbp=$3
+			[[ -n $4 ]] && local query="use $4"
 		else
 			local dbu="admin"
 			local dbp=$ADMIN_PASS
 		fi
 		
-		sudo mysql --connect-timeout=10 --user=$dbu -p$dbp -e "quit"
+		sudo mysql --connect-timeout=10 --user=$dbu -p$dbp -e "$query"
 		if [[ $? != "0" ]]; then
 			echo "${red}============================================" >&2
 			echo "    [Error]  Database conection failed." >&2
@@ -601,15 +605,14 @@ is_url() {
 is_ssl() {
 	[[ -f /etc/nginx/sites-available/$1 && -n $(sed -n -e '/WebinolyNginxServerStart/,$p' /etc/nginx/sites-available/$1 | grep -F "ssl_certificate_key") ]] && echo "true" || echo "false"
 }
-
-
 is_ssl_le() {
 	[[ -f /etc/nginx/sites-available/$1 && -n $(sed -n -e '/WebinolyNginxServerStart/,$p' /etc/nginx/sites-available/$1 | grep -F "ssl_certificate_key /etc/letsencrypt/live/") && -z $(grep -F "WebinolySSLCustomCert" /etc/nginx/sites-available/$1) ]] && echo "true" || echo "false"
 }
-
-
 is_ssl_staging() {
 	[[ -f /etc/letsencrypt/renewal/$1.conf && -n $(grep -E "^server = " /etc/letsencrypt/renewal/$1.conf | cut -d'=' -f 2 -s | grep -F "acme-staging-") ]] && echo "true" || echo "false"
+}
+is_ssl_wildcard() {
+	[[ -f /etc/letsencrypt/renewal/$1.conf && -n $(sudo certbot certificates --cert-name $1 2>/dev/null | grep -E "Domains:.* \*.$1") ]] && echo "true" || echo "false"
 }
 
 
@@ -1045,10 +1048,11 @@ config_fastcgi_cache() {
 		fi
 		
 		local mainfile="/etc/nginx/conf.d/webinoly.conf"
-		local config_cache=$2
+		local cache_valid=$2
 	else
 		local timefile="/etc/nginx/conf.d/fastcgi.conf"
 		local mainfile="/etc/nginx/conf.d/fastcgi.conf"
+		[[ -n $config_cache && -z $cache_valid ]] && cache_valid=$config_cache  # Will be removed!
 	fi
 	
 
@@ -1072,7 +1076,7 @@ config_fastcgi_cache() {
 	fi
 
 	
-	if [[ $config_cache == true ]]; then
+	if [[ $cache_valid == true ]]; then
 		echo "${gre}"
 		echo "**********************************************************************"
 		echo "*************      Set Nginx Cache new time values      **************"
@@ -1091,12 +1095,12 @@ config_fastcgi_cache() {
 		read -p "   Set new value: " oth
 		oth=${oth:-$othval}
 		echo ""
-	elif [[ $(echo "${config_cache}" | cut -c-1) == "[" && $(echo "${config_cache}" | rev | cut -c-1) == "]" ]]; then
-		custombegin=$(echo "${config_cache}" | cut -c-1)
-		customlast=$(echo "${config_cache}" | rev | cut -c-1)
+	elif [[ $(echo "${cache_valid}" | cut -c-1) == "[" && $(echo "${cache_valid}" | rev | cut -c-1) == "]" ]]; then
+		custombegin=$(echo "${cache_valid}" | cut -c-1)
+		customlast=$(echo "${cache_valid}" | rev | cut -c-1)
 		
 		# No need for check var lenght to prevent errors, the previous condition is enough in this case.
-		cachedata=${config_cache:1:-1}
+		cachedata=${cache_valid:1:-1}
 			
 		hit=$(echo "${cachedata}" | cut -d',' -f 1 )
 		ina=$(echo "${cachedata}" | cut -d',' -f 2 )
@@ -1302,4 +1306,36 @@ if (\$http_cookie $sign $value) {
 	fi
 }
 
+
+smtp_backup() {
+	if [[ $(conf_read smtp) == "true" ]]; then
+		sudo touch /var/www/webinoly_backup_smtp
+		echo "$(sudo sed -n 1p /etc/mailname) $(sudo sed -n 1p /etc/postfix/sasl_passwd)" > /var/www/webinoly_backup_smtp
+	fi
+}
+smtp_backup_recovery() {
+	if [[ -s /var/www/webinoly_backup_smtp ]]; then
+		local smtpdata=$(sudo sed -n 1p /var/www/webinoly_backup_smtp)
+		local main=$(echo $smtpdata | cut -d' ' -f 1 -s)
+		local host=$(echo $smtpdata | cut -d' ' -f 2 -s | cut -d':' -f 1 -s)
+		local user=$(echo $smtpdata | cut -d' ' -f 3 -s | cut -d':' -f 1 -s)
+		local pass=$(echo $smtpdata | cut -d' ' -f 3 -s | cut -d':' -f 2 -s)
+		sudo rm -rf /var/www/webinoly_backup_smtp
+		
+		if [[ -n $host && -n $user && -n $pass && -n $main ]]; then
+			sudo webinoly -smtp=[$host,$user,$pass,$main]
+		else
+			echo "${red}[ERROR] SMTP Configuration recovery failed! ${end}"
+		fi
+	fi
+}
+
+
+help_message() {
+	echo ""
+	echo "${blu}${bol}Thanks for using Webinoly!${end}"
+	echo "${blu}We have put a lot of time and effort into creating the most awesome, detailed and extensive documentation just for you."
+	echo "${dim}Link: https://webinoly.com/en/documentation/ ${end}"
+	echo ""
+}
 
diff --git a/assets/webinoly/lib/sites b/assets/webinoly/lib/sites
--- a/assets/webinoly/lib/sites
+++ b/assets/webinoly/lib/sites
@@ -1045,6 +1045,9 @@ wp_multisite_convertion() {
 		if [[ $passed == "subdomain" ]]; then
 			wp_config_write $domain SUBDOMAIN_INSTALL true $subfolder
 			sudo sed -i "/server_name /c \	server_name $domain *.$domain;" /etc/nginx/sites-available/$domain
+			
+			[[ -f /etc/letsencrypt/renewal/${domain}.conf && $(is_ssl_wildcard $domain) != "true" ]] && echo "${dim}[WARNING] A Wildcard SSL Cert is recommended, a cert was found but seems like it's not wildcard!${end}"
+			
 			echo "${gre}Subdomain Multisite configuration has been successfully completed!${end}"
 		elif [[ $passed == "subdirectory" ]]; then
 			wp_config_write $domain SUBDOMAIN_INSTALL false $subfolder
@@ -1228,6 +1231,36 @@ full_empty_not_allowed() {
 }
 
 
+query_string_cache_default() {
+	if [[ $(is_wp $domain $subfolder) == "true" && -f /etc/nginx/apps.d/$domain$subname-wpcache.conf ]]; then
+		local cachefile="/etc/nginx/apps.d/$domain$subname-wpcache.conf"
+	elif [[ $(is_php $domain $subfolder) == "true" && -f /etc/nginx/apps.d/$domain$subname-phpcache.conf ]]; then
+		local cachefile="/etc/nginx/apps.d/$domain$subname-phpcache.conf"
+	elif [[ $(is_proxy $domain $subfolder) == "true" && -f /etc/nginx/apps.d/$domain$subname-proxy.conf ]]; then
+		local cachefile="/etc/nginx/apps.d/$domain$subname-proxy.conf"
+	else
+		echo "${red}[ERROR] Custom Cache not found! ${dim}(Must be enabled at least once before you can add these custom rules)${end}"
+		exit 1
+	fi
+	
+	if ! [[ $query_string_cache_default =~ ^(all|never)$ ]]; then
+		echo "${red}[ERROR] Please, enter a valid value for Query-String Cache default!${dim} ('all' or 'never')${end}"
+		exit 1
+	elif [[ $query_string_cache_default == "all" ]]; then
+		sudo sed -i "/# CacheQueryStringDefault/,/# CacheRuleEnd/{/.*/d}" $cachefile
+		echo "${gre}Query-String Cache default successfully updated!${dim} (All will be cached by default, except for individual rules if added)${end}"
+	elif [[ $query_string_cache_default == "never" ]]; then
+		if [[ -z $(grep -F "# CacheQueryStringDefault" $cachefile) ]]; then
+			local mark="_$(echo $domain | sed "s/[^0-9A-Za-z]/_/g")${subname}"
+			sudo sed -i "/set \$skip_cache${mark} 0;/a # CacheQueryStringDefault\nif (\$query_string) {\n	set \$skip_cache${mark} 1;\n}\n# CacheRuleEnd" $cachefile
+			echo "${gre}Query-String Cache default successfully updated!${dim} (Never will be cached, except for individual rules if added)${end}"
+		else
+			echo "${gre}Query-String (Never) Cache default is already enabled!${end}"
+		fi
+	fi
+}
+
+
 wp_cache() {
 	if [[ $cache == "off" ]]; then
 		api-events_update si9
@@ -1264,6 +1297,8 @@ wp_cache() {
 			fi
 			
 			echo "${gre}Custom FastCGI Cache in${blu} $domain ${gre}has been disabled!${end}"
+			[[ -n $reset && -n $subfolder ]] && site $domain -cache=custom -reset -subfolder=$subfolder
+			[[ -n $reset && -z $subfolder ]] && site $domain -cache=custom -reset
 		elif [[ $(is_cache $domain $subfolder) == "proxy" ]]; then
 			sudo sed -i "/proxy_cache .*;/c \	proxy_cache off;" /etc/nginx/apps.d/$domain$subname-proxy.conf
 			echo "${gre}Proxy Cache in${blu} $domain$subfolder ${gre}has been disabled!${end}"
@@ -1342,8 +1377,11 @@ wp_cache() {
 			[[ -f /etc/nginx/conf.d/webinoly.conf && ! -s /etc/nginx/conf.d/webinoly.conf ]] && sudo rm /etc/nginx/conf.d/webinoly.conf
 		elif [[ -n $query_string_never_cache || $query_string_cache || $skip_cache || -n $skip_cookie_cache ]]; then
 			custom_cache_global -site
-		elif [[ -n $times ]]; then
-			config_fastcgi_cache -site $times
+		elif [[ -n $query_string_cache_default ]]; then
+			query_string_cache_default
+		elif [[ -n $cache_valid || -n $times ]]; then
+			[[ -n $times && -z $cache_valid ]] && cache_valid=$times  # Will be removed!
+			config_fastcgi_cache -site $cache_valid
 		elif [[ $(is_cache $domain $subfolder) == "false" && $(is_proxy $domain $subfolder) == "true" && -n $(grep -F "# WebinolyProxyCacheStart" /etc/nginx/apps.d/$domain$subname-proxy.conf) ]]; then
 			sudo sed -i "/proxy_cache .*;/c \	proxy_cache $(echo $domain | sed "s/[^0-9A-Za-z]/_/g")${subname};" /etc/nginx/apps.d/$domain$subname-proxy.conf
 			echo "${gre}Custom Proxy Cache in${blu} $domain$subfolder ${gre}has been successfully enabled! ${end}"
@@ -1393,8 +1431,17 @@ wp_cache() {
 				echo "fastcgi_cache_path /run/nginx-cache/${dom}${subname} levels=1:2 keys_zone=${dom}${subname}:50m max_size=${cachesize}m inactive=7d;" >> /etc/nginx/conf.d/webinoly.conf
 				
 				echo -e "# Webinoly Custom FastCGI Cache File \n" >> /etc/nginx/apps.d/$domain$subname-${fn}.conf
-				sudo cat /etc/nginx/common/wpfc.conf >> /etc/nginx/apps.d/$domain$subname-${fn}.conf
-				sudo sed -i '/# WPFC NGINX CONFIGURATION/,/# Use cached or actual file if they exists/{/.*/d}' /etc/nginx/apps.d/$domain$subname-${fn}.conf
+				
+				if [[ $fn == "phpcache" && $(conf_read php-info) != "false" ]]; then
+					sudo cat /etc/nginx/common/phpx.conf >> /etc/nginx/apps.d/$domain$subname-${fn}.conf
+				else
+					sudo cat /etc/nginx/common/php.conf >> /etc/nginx/apps.d/$domain$subname-${fn}.conf
+				fi
+				
+				sudo sed -i '/# PHP NGINX CONFIGURATION/,/# DO NOT MODIFY, ALL/{/.*/d}' /etc/nginx/apps.d/$domain$subname-${fn}.conf
+				sudo sed -i "/fastcgi_pass php;/a	fastcgi_cache WORDPRESS;" /etc/nginx/apps.d/$domain$subname-${fn}.conf
+				sudo sed -i "/fastcgi_pass php;/a	fastcgi_no_cache \$skip_cache;" /etc/nginx/apps.d/$domain$subname-${fn}.conf
+				sudo sed -i "/fastcgi_pass php;/a	fastcgi_cache_bypass \$skip_cache;" /etc/nginx/apps.d/$domain$subname-${fn}.conf
 				sudo sed -i '/fastcgi_cache WORDPRESS;/r /etc/nginx/conf.d/fastcgi.conf' /etc/nginx/apps.d/$domain$subname-${fn}.conf
 				sudo sed -i '/# FastCGI cache settings/,/fastcgi_cache_path /{/.*/d}' /etc/nginx/apps.d/$domain$subname-${fn}.conf
 				sudo sed -i "/fastcgi_cache WORDPRESS;/c \	fastcgi_cache ${dom}${subname};" /etc/nginx/apps.d/$domain$subname-${fn}.conf
@@ -1416,7 +1463,8 @@ wp_cache() {
 				echo "${gre}${dim}FastCGI Cache configuration file found!${end}"
 			fi
 			
-			[[ -n $times && $times != "true" ]] && config_fastcgi_cache -site $times
+			[[ -n $times && $times != "true" ]] && config_fastcgi_cache -site $times   # Will be removed!
+			[[ -n $cache_valid && $cache_valid != "true" && -z $times ]] && config_fastcgi_cache -site $cache_valid
 			
 			echo "${gre}"
 			echo "Custom FastCGI Cache in${blu} $domain$subfolder ${gre}has been successfully enabled! ${end}"
diff --git a/assets/webinoly/lib/webin b/assets/webinoly/lib/webin
--- a/assets/webinoly/lib/webin
+++ b/assets/webinoly/lib/webin
@@ -2,469 +2,6 @@
 source /opt/webinoly/lib/install
 
 
-# Verify Integrity of all "required" files and system
-webinoly_verify() {
-	local error="0"
-	local warning="0"
-	local info="0"
-	echo "${blu}Verifying integrity of the entire Webinoly system..."
-	echo "${red}"
-	
-	# Webinoly
-	if [[ ! -f /opt/webinoly/lib/general ]]; then
-		echo "[ERROR] File: /opt/webinoly/lib/general not found!"
-		error="1"
-	fi
-	if [[ ! -f /opt/webinoly/lib/install ]]; then
-		echo "[ERROR] File: /opt/webinoly/lib/install not found!"
-		error="1"
-	fi
-	if [[ ! -f /opt/webinoly/lib/sites ]]; then
-		echo "[ERROR] File: /opt/webinoly/lib/install not found!"
-		error="1"
-	fi
-	if [[ ! -f /opt/webinoly/lib/site-ssl ]]; then
-		echo "[ERROR] File: /opt/webinoly/lib/install not found!"
-		error="1"
-	fi
-	if [[ ! -f /opt/webinoly/lib/webin ]]; then
-		echo "[ERROR] File: /opt/webinoly/lib/install not found!"
-		error="1"
-	fi
-	if [[ ! -f /opt/webinoly/lib/update ]]; then
-		echo "[ERROR] File: /opt/webinoly/lib/install not found!"
-		error="1"
-	fi
-	if [[ ! -f /opt/webinoly/lib/public_suffix_list.dat ]]; then
-		echo "[ERROR] File: /opt/webinoly/lib/install not found!"
-		error="1"
-	fi
-	if [[ ! -f /opt/webinoly/lib/timezone.dat ]]; then
-		echo "[ERROR] File: /opt/webinoly/lib/install not found!"
-		error="1"
-	fi
-	if [[ ! -f /opt/webinoly/lib/api-events_sample ]]; then
-		echo "[ERROR] File: /opt/webinoly/lib/install not found!"
-		error="1"
-	fi
-	if [[ ! -f /opt/webinoly/templates/template-site-php ]]; then
-		echo "[ERROR] File: /opt/webinoly/templates/template-site-php not found!"
-		error="1"
-	fi
-	if [[ ! -f /opt/webinoly/templates/template-site-proxy ]]; then
-		echo "[ERROR] File: /opt/webinoly/templates/template-site-php not found!"
-		error="1"
-	fi
-	if [[ ! -f /opt/webinoly/templates/template-site-ssl ]]; then
-		echo "[ERROR] File: /opt/webinoly/templates/template-site-php not found!"
-		error="1"
-	fi
-	if [[ ! -f /opt/webinoly/templates/template-site-sslredirect ]]; then
-		echo "[ERROR] File: /opt/webinoly/templates/template-site-php not found!"
-		error="1"
-	fi
-	if [[ ! -f /opt/webinoly/templates/template-site-wwwredirect ]]; then
-		echo "[ERROR] File: /opt/webinoly/templates/template-site-php not found!"
-		error="1"
-	fi
-	if [[ ! -f /opt/webinoly/templates/nginx/nginx.conf ]]; then
-		echo "[ERROR] File: /opt/webinoly/templates/nginx/nginx.conf not found!"
-		error="1"
-	fi
-	if [[ ! -f /opt/webinoly/templates/nginx/22222 ]]; then
-		echo "[ERROR] File: /opt/webinoly/templates/nginx/22222 not found!"
-		error="1"
-	fi
-	if [[ ! -f /opt/webinoly/templates/nginx/conf.d/fastcgi.conf ]]; then
-		echo "[ERROR] File: /opt/webinoly/templates/nginx/conf.d/fastcgi.conf not found!"
-		error="1"
-	fi
-	if [[ ! -f /opt/webinoly/templates/nginx/conf.d/upstream.conf ]]; then
-		echo "[ERROR] File: /opt/webinoly/templates/nginx/conf.d/upstream.conf not found!"
-		error="1"
-	fi
-	if [[ ! -f /opt/webinoly/templates/nginx/common/acl.conf ]]; then
-		echo "[ERROR] File: /opt/webinoly/templates/nginx/common/acl.conf not found!"
-		error="1"
-	fi
-	if [[ ! -f /opt/webinoly/templates/nginx/common/locations.conf ]]; then
-		echo "[ERROR] File: /opt/webinoly/templates/nginx/common/locations.conf not found!"
-		error="1"
-	fi
-	if [[ ! -f /opt/webinoly/templates/nginx/common/php.conf ]]; then
-		echo "[ERROR] File: /opt/webinoly/templates/nginx/common/php.conf not found!"
-		error="1"
-	fi
-	if [[ ! -f /opt/webinoly/templates/nginx/common/wpcommon.conf ]]; then
-		echo "[ERROR] File: /opt/webinoly/templates/nginx/common/wpcommon.conf not found!"
-		error="1"
-	fi
-	if [[ ! -f /opt/webinoly/templates/nginx/common/wpfc.conf ]]; then
-		echo "[ERROR] File: /opt/webinoly/templates/nginx/common/wpfc.conf not found!"
-		error="1"
-	fi
-	if [[ ! -f /opt/webinoly/templates/nginx/common/wpsubdir.conf ]]; then
-		echo "[ERROR] File: /opt/webinoly/templates/nginx/common/wpsubdir.conf not found!"
-		error="1"
-	fi
-	if [[ ! -f /opt/webinoly/templates/nginx/common/headers-html.conf ]]; then
-		echo "[ERROR] File: /opt/webinoly/templates/nginx/common/headers-html.conf not found!"
-		error="1"
-	fi
-	if [[ ! -f /opt/webinoly/templates/nginx/common/headers-http.conf ]]; then
-		echo "[ERROR] File: /opt/webinoly/templates/nginx/common/headers-http.conf not found!"
-		error="1"
-	fi
-	if [[ ! -f /opt/webinoly/templates/nginx/common/headers-https.conf ]]; then
-		echo "[ERROR] File: /opt/webinoly/templates/nginx/common/headers-https.conf not found!"
-		error="1"
-	fi
-	if [[ ! -f /opt/webinoly/webinoly.conf ]]; then
-		echo "[ERROR] File: /opt/webinoly/webinoly.conf not found!"
-		error="1"
-	fi
-	if [[ ! -f /usr/bin/webinoly ]]; then
-		echo "[ERROR] File: /usr/bin/webinoly not found!"
-		error="1"
-	fi
-	if [[ ! -f /usr/bin/site ]]; then
-		echo "[ERROR] File: /usr/bin/site not found!"
-		error="1"
-	fi
-	if [[ ! -f /usr/bin/httpauth ]]; then
-		echo "[ERROR] File: /usr/bin/httpauth not found!"
-		error="1"
-	fi
-	if [[ ! -f /usr/bin/log ]]; then
-		echo "[ERROR] File: /usr/bin/log not found!"
-		error="1"
-	fi
-	if [[ ! -f /usr/bin/stack ]]; then
-		echo "[ERROR] File: /usr/bin/stack not found!"
-		error="1"
-	fi
-	
-	# NGINX
-	if [[ $(conf_read nginx) == "true" ]]; then
-		if [[ ! -f /etc/nginx/nginx.conf ]]; then
-			echo "[ERROR] File: /etc/nginx/nginx.conf not found!"
-			error="1"
-		fi
-	fi
-	if [[ $(conf_read nginx) != "true" ]]; then
-		if [[ -f /etc/nginx/nginx.conf ]]; then
-			echo "[WARNING] Seems like NGINX is installed but Webinoly can not detect it!"
-			warning="1"
-		fi
-		if [[ -f /etc/nginx/fastcgi.conf ]]; then
-			echo "[WARNING] Seems like NGINX is installed but Webinoly can not detect it!"
-			warning="1"
-		fi
-	fi
-	
-	# NGINX Optim
-	if [[ $(conf_read nginx-optim) == "true" ]]; then
-		if [[ ! -f /etc/nginx/fastcgi_params ]]; then
-			echo "[ERROR] File: /etc/nginx/fastcgi_params not found!"
-			error="1"
-		fi
-		if [[ $(conf_read php) == "true" && ! ( -s /etc/nginx/.htpasswd || ( -n $(conf_read tools-site) && -s /etc/nginx/apps.d/.htpasswd-$(conf_read tools-site) )) ]]; then
-			echo "[INFO] HTTP Authentication Credentials not found!"
-			info="1"
-		fi
-		if [[ ! -f /etc/nginx/conf.d/fastcgi.conf ]]; then
-			echo "[ERROR] File: /etc/nginx/conf.d/fastcgi.conf not found!"
-			error="1"
-		fi
-		if [[ ! -f /etc/nginx/conf.d/upstream.conf ]]; then
-			echo "[ERROR] File: /etc/nginx/conf.d/upstream.conf not found!"
-			error="1"
-		fi
-		if [[ ! -f /etc/nginx/common/acl.conf ]]; then
-			echo "[ERROR] File: /etc/nginx/common/acl.conf not found!"
-			error="1"
-		fi
-		if [[ ! -f /etc/nginx/common/locations.conf ]]; then
-			echo "[ERROR] File: /etc/nginx/common/locations.conf not found!"
-			error="1"
-		fi
-		if [[ ! -f /etc/nginx/common/php.conf ]]; then
-			echo "[ERROR] File: /etc/nginx/common/php.conf not found!"
-			error="1"
-		fi
-		if [[ ! -f /etc/nginx/common/wpcommon.conf ]]; then
-			echo "[ERROR] File: /etc/nginx/common/wpcommon.conf not found!"
-			error="1"
-		fi
-		if [[ ! -f /etc/nginx/common/wpfc.conf ]]; then
-			echo "[ERROR] File: /etc/nginx/common/wpfc.conf not found!"
-			error="1"
-		fi
-		if [[ ! -f /etc/nginx/common/wpsubdir.conf ]]; then
-			echo "[ERROR] File: /etc/nginx/common/wpsubdir.conf not found!"
-			error="1"
-		fi
-		if [[ ! -f /etc/nginx/common/headers-html.conf ]]; then
-			echo "[ERROR] File: /etc/nginx/common/headers-html.conf not found!"
-			error="1"
-		fi
-		if [[ ! -f /etc/nginx/common/headers-http.conf ]]; then
-			echo "[ERROR] File: /etc/nginx/common/headers-http.conf not found!"
-			error="1"
-		fi
-		if [[ ! -f /etc/nginx/common/headers-https.conf ]]; then
-			echo "[ERROR] File: /etc/nginx/common/headers-https.conf not found!"
-			error="1"
-		fi
-	fi
-	
-	# NGINX Tools
-	if [[ $(conf_read nginx-tool) == "true" ]]; then
-		if [[ ! -f /etc/nginx/sites-available/$(conf_read tools-port) && $(conf_read php) == "true" ]]; then
-			echo "[ERROR] File: /etc/nginx/sites-available/$(conf_read tools-port) not found!"
-			error="1"
-		fi
-		if [[ ! -d /var/www/$(conf_read tools-port) && $(conf_read php) == "true" ]]; then
-			echo "[ERROR] Folder: /var/www/$(conf_read tools-port) not found!"
-			error="1"
-		fi
-		if [[ -z $(conf_read tools-port) ]]; then
-			echo "[ERROR] Port Tools not found!"
-			error="1"
-		fi
-	fi
-	if [[ $(conf_read nginx-tool) != "true" && -n $(conf_read tools-port) ]]; then
-		if [[ -f /etc/nginx/sites-available/$(conf_read tools-port) || -d /var/www/$(conf_read tools-port) ]]; then
-			echo "[WARNING] Seems like Nginx Tools are enabled but Webinoly can not detect it!"
-			warning="1"
-		fi
-	fi
-	
-	# NGINX Conf check
-	if [[ $(conf_read nginx) != "true" && ( $(conf_read nginx-optim) == "true" || $(conf_read nginx-tool) == "true" ) ]]; then
-		echo "[WARNING] NGINX Configuration corrupted!"
-		warning="1"
-	fi
-	
-	# PHP
-	if [[ ! -f /etc/php/$(conf_read php-ver)/fpm/php.ini && $(conf_read php) == "true" ]]; then
-		echo "[ERROR] File: /etc/php/$(conf_read php-ver)/fpm/php.ini not found!"
-		error="1"
-	elif [[ -f /etc/php/$(conf_read php-ver)/fpm/php.ini && $(conf_read php) != "true" ]]; then
-		echo "[WARNING] Seems like PHP is installed but Webinoly can not detect it!"
-		warning="1"
-	fi
-	
-	# PHP Optim
-	if [[ $(conf_read php-optim) == "true" ]]; then
-		if [[ ! -f /etc/php/$(conf_read php-ver)/fpm/php-fpm.conf ]]; then
-			echo "[ERROR] File: /etc/php/$(conf_read php-ver)/fpm/php-fpm.conf not found!"
-			error="1"
-		fi
-		if [[ ! -f /etc/php/$(conf_read php-ver)/fpm/pool.d/www.conf ]]; then
-			echo "[ERROR] File: /etc/php/$(conf_read php-ver)/fpm/pool.d/www.conf not found!"
-			error="1"
-		fi
-		if [[ ! -f /opt/webinoly/templates/source/www.conf ]]; then
-			echo "[ERROR] File: /opt/webinoly/templates/source/www.conf not found!"
-			error="1"
-		fi
-		if [[ ! -f /opt/webinoly/templates/source/php.ini ]]; then
-			echo "[ERROR] File: /opt/webinoly/templates/source/php.ini not found!"
-			error="1"
-		fi
-	fi
-	
-	# PHP Tools
-	if [[ $(conf_read php-tool) == "true" && $(conf_read nginx) == "true" ]]; then
-		if [[ ! -f /var/www/$(conf_read tools-port)/htdocs/status ]]; then
-			echo "[ERROR] File: /var/www/$(conf_read tools-port)/htdocs/status not found!"
-			error="1"
-		fi
-		if [[ ! -f /var/www/$(conf_read tools-port)/htdocs/php/index.php ]]; then
-			echo "[ERROR] File: /var/www/$(conf_read tools-port)/htdocs/php/index.php not found!"
-			error="1"
-		fi
-	fi
-	if [[ $(conf_read php-tool) != "true" && $(conf_read nginx) == "true" ]]; then
-		if [[ -f /var/www/$(conf_read tools-port)/htdocs/status ]]; then
-			echo "[WARNING] Seems like PHP Tools are enabled but Webinoly can not detect it!"
-			warning="1"
-		fi
-		if [[ -f /var/www/$(conf_read tools-port)/htdocs/php/index.php ]]; then
-			echo "[WARNING] Seems like PHP Tools are enabled but Webinoly can not detect it!"
-			warning="1"
-		fi
-	fi
-	
-	# PHP Conf check
-	if [[ $(conf_read php) != "true" && ( $(conf_read php-optim) == "true" || $(conf_read php-tool) == "true" ) ]]; then
-		echo "[WARNING] PHP Configuration corrupted!"
-		warning="1"
-	fi
-	
-	# MySQL
-	if [[ ! -d /etc/mysql && $(conf_read mysql) == "true" ]]; then
-		echo "[ERROR] Folder: /etc/mysql not found!"
-		error="1"
-	elif [[ -d /etc/mysql && $(conf_read mysql) != "true" ]]; then
-		echo "[WARNING] Seems like MySQL is installed but Webinoly can not detect it!"
-		warning="1"
-	fi
-	
-	# MySQL Tools
-	if [[ ! -d /var/www/$(conf_read tools-port)/htdocs/pma && $(conf_read mysql-tool) == "true" ]]; then
-		echo "[ERROR] Folder: /var/www/$(conf_read tools-port)/htdocs/pma not found!"
-		error="1"
-	elif [[ ( -d /var/www/$(conf_read tools-port)/htdocs/pma || -d /usr/share/phpmyadmin ) && $(conf_read mysql-tool) != "true" ]]; then
-		echo "[WARNING] Seems like MySQL Tools (PhpMyAdmin) are enabled but Webinoly can not detect it!"
-		warning="1"
-	fi
-	
-	# MySQL Conf check
-	if [[ $(conf_read mysql) != "true" && $(conf_read mysql-tool) == "true" ]]; then
-		echo "[WARNING] MySQL Configuration corrupted!"
-		warning="1"
-	fi
-	
-	# Web Tools
-	if [[ $(conf_read php-tool) == "true" ]]; then
-		if [[ ! -d /etc/redis ]]; then
-			echo "[ERROR] Folder: /etc/redis not found!"
-			error="1"
-		fi
-		if [[ ! -d /etc/postfix ]]; then
-			echo "[ERROR] Folder: /etc/postfix not found!"
-			error="1"
-		fi
-	fi
-	if [[ $(conf_read nginx-tool) == "true" ]]; then
-		if [[ ! -f /usr/bin/duplicity ]]; then
-			echo "[ERROR] File: /usr/bin/duplicity not found!"
-			error="1"
-		fi
-		if [[ ! -f /usr/bin/duply ]]; then
-			echo "[ERROR] File: /usr/bin/duply not found!"
-			error="1"
-		fi
-		if [[ ! -L /usr/bin/certbot ]]; then
-			echo "[ERROR] File: /usr/bin/certbot not found!"
-			error="1"
-		fi
-	fi
-	
-	# Check if services are running and check configurations
-	if ! systemctl is-active --quiet nginx && [[ $(conf_read nginx) == "true" ]]; then
-		echo "[ERROR] Nginx service not running!"
-		error="1"
-	fi
-	if ! systemctl is-active --quiet php$(conf_read php-ver)-fpm && [[ $(conf_read php) == "true" ]]; then
-		echo "[ERROR] PHP service not running!"
-		error="1"
-	fi
-	if ! systemctl is-active --quiet mysql && [[ $(conf_read mysql) == "true" ]]; then
-		echo "[ERROR] MySQL (MariaDB) service not running!"
-		error="1"
-	fi
-	if ! systemctl is-active --quiet redis-server && [[ $(conf_read php-tool) == "true" ]]; then
-		echo "[ERROR] Redis service not running!"
-		error="1"
-	fi
-	if ! systemctl is-active --quiet memcached && [[ $(conf_read php-tool) == "true" ]]; then
-		echo "[ERROR] Memcached service not running!"
-		error="1"
-	fi
-	if ! systemctl is-active --quiet postfix && [[ $(conf_read php-tool) == "true" ]]; then
-		echo "[ERROR] Postfix service not running!"
-		error="1"
-	fi
-	
-	if ! sudo nginx -t 2>/dev/null && [[ $(conf_read nginx) == "true" ]]; then
-		echo "[ERROR] Nginx Configuration check failed!"
-		error="1"
-	fi
-	
-	local ROOT_PASS=$( echo $(conf_read mysql-root) | openssl enc -d -a -salt )
-	[[ -z $ROOT_PASS ]] && local ROOT_PASS="dUmb"
-	if ! sudo mysql --connect-timeout=10 --user=root -p$ROOT_PASS -e "quit" 2>/dev/null && [[ $(conf_read mysql) == "true" ]]; then
-		echo "[ERROR] MySQL Connection to localhost failed! (root)"
-		error="1"
-	fi
-	
-	if ! sudo mysql --connect-timeout=10 --user=admin -p$ADMIN_PASS -e "quit" 2>/dev/null && [[ $(conf_read mysql) == "true" ]]; then
-		echo "[ERROR] MySQL Connection to localhost failed! (admin)"
-		error="1"
-	fi
-	
-	
-	# Linux Optim
-	if [[ $(conf_read linux-optim) == "true" && ( -z $swapm || $swapm == "0" ) && $(conf_read swap-mem) != 0 ]]; then
-		echo "[ERROR] SWAP Memory File not found!"
-		error="1"
-	fi
-
-	# Check for Tools and Default site.
-	if [[ -n $(conf_read default-site) && ! ( $(conf_read default-site) =~ ^(default|blackhole)$ ) && ! -L /etc/nginx/sites-enabled/$(conf_read default-site) ]]; then
-		echo "[WARNING] Default site not found or is not enabled!"
-		warning="1"
-	fi
-	if [[ -n $(conf_read tools-site) && ! -L /etc/nginx/sites-enabled/$(conf_read tools-site) ]]; then
-		echo "[WARNING] Tools site not found or is not enabled!"
-		warning="1"
-	fi
-	
-	# Check for PHP and MySQL version
-	if [[ $(conf_read php) == "true" && $(php -v | grep -m1 "" | sed 's/PHP \([^\-]*\).*/\1/' | cut -f 1-2 -d'.') != "7.4" ]]; then
-		echo "[INFO] PHP v7.4 is recommended to get an optimal perfomance!"
-	fi
-	if [[ $(conf_read mysql) == "true" && $(sudo mysql --version  | sed 's/.*Distrib \([^\-]*\).*/\1/' | cut -f 1-2 -d'.') != "10.5" ]]; then
-		echo "[INFO] MariaDB (MySQL) v10.5 is recommended to get an optimal perfomance!"
-	fi
-	
-	# Check OS support
-	if [[ $(lsb_release -i | cut -d':' -f 2 | xargs) != "Ubuntu" ]]; then
-		echo "[ERROR] This Operating System is not supported!"
-		error="1"
-	elif [[ $(check_ubuntu_release) != "true" ]]; then
-		echo "[ERROR] This Ubuntu version is not supported!"
-		error="1"
-	fi
-	# Check for sudo/root privileges
-	if ! $(groups $USERNAME | grep &>/dev/null '\bsudo\b' || groups $USERNAME | grep &>/dev/null '\broot\b'); then
-		echo "[WARNING] This user has no Sudo/Root privileges!"
-		warning="1"
-	fi
-
-	# Check for SSL Orphan-Certs
-	for cert in "/etc/letsencrypt/live"/*
-	do
-		domain=$(echo $cert | cut -f 5 -d "/")
-		if [[ -d $cert && ! -f /etc/nginx/sites-available/$domain ]]; then
-			echo "[INFO] SSL Orphan-Cert found ($domain)!"
-			info="1"
-		fi
-	done
-	
-	
-	echo ""
-	if [ $error != 0 ]; then
-		echo "*******************************************************"
-		echo "********      ${gre}> > >  E R R O R < < <${red}        ***********"
-		echo "********   ${gre}System could not work properly${red}   ***********"
-		echo "******************************************************* ${end}"
-		exit 1
-	elif [ $warning != 0 ]; then
-		echo "***********************************************************************************************************"
-		echo "********      ${gre}[ W A R N I N G ] System seems to be corrupted and could not work properly${red}        ***********"
-		echo "*********************************************************************************************************** ${end}"
-		exit 2
-	else
-		echo "${gre}Integrity test passed!! ${end}"
-		exit 0
-	fi
-}
-
-
 system_info() {
 	[[ $ram == 0 ]] && local ramv="${ramb}Mb" || ramv="${ram}Gb"
 	[[ $swap == 0 ]] && local swapv="${swapm}Mb" || swapv="${swap}Gb"
@@ -732,25 +269,27 @@ webinoly_update() {
 		exit 1
 	fi
 	
+	local currentver=$(conf_read app-version)
+	
 	if [[ -n $update && $update != true ]]; then
-		branch="-ver=${update}"
+		local branch="-ver=${update}"
 	else
-		checkver=$(wget --timeout=10 -t 1 -qO- https://api.webinoly.com/check?text=true)
-		currentver=$(conf_read app-version)
+		local checkver=$(wget --timeout=10 -t 1 -qO- https://api.webinoly.com/check?text=true)
 		if [[ -n $checkver && -n $currentver && ${currentver//.} -ge ${checkver//.} ]]; then
-			echo "${gre}You currently have the latest version!${end}"
+			echo "${gre}You currently have the latest version!${dim} (v${checkver})${end}"
 			exit 0
 		elif [[ -z $checkver || -z $currentver ]]; then
 			echo "${red}[ERROR] Version number unavailable!${end}"
 			exit 1
 		else
 			echo "${dim}Updating...${end}"
+			echo "${blu}${dim}Your current version 'v${currentver}' will be updated to the newest 'v${checkver}' ${end}"
 		fi
 	fi
 	
 	sudo wget --timeout=15 -t 1 --referer="https://update.webinoly.com/?ver=${app_version}" -qrO weby https://qrok.es/wyupd && sudo bash weby upd $branch
 	
-	[[ $? == 0 ]] && echo "${gre}Webinoly App has been updated successfully!${end}"
+	[[ $? == 0 ]] && echo "${gre}Webinoly App has been updated successfully!${dim} (Updated to: v$(conf_read app-version))${end}"
 	api-events_update wy1s
 }
 
@@ -1860,6 +1399,25 @@ http_header_csp() {
 		
 		echo "$header_csp" >> /opt/webinoly/templates/source/csp_webinoly.data
 		echo "${gre}HTTP Header successfully configured!${end}"
+	fi
+}
+
+
+http_header_permission_policy() {
+	if [[ $(conf_read nginx) == "true" ]]; then
+		if [[ $header_permission_policy == "off" ]]; then
+			sudo sed -i '/^add_header Permission-Policy/d' /etc/nginx/common/headers-html.conf
+			echo "${gre}Permission Policy Header successfully disabled!${end}"
+		elif [[ $header_permission_policy == "floc" ]]; then
+			echo "add_header Permission-Policy \"interest-cohort=()\";" >> /etc/nginx/common/headers-html.conf
+			echo "${gre}HTTP Header successfully configured!${end}"
+		else
+			echo "${red}[ERROR] Invalid value!${end}"
+			exit 1
+		fi
+	else
+		echo "${red}[ERROR] Nginx not found!${end}"
+		exit 1
 	fi
 }
 
diff --git a/assets/webinoly/plugins/site b/assets/webinoly/plugins/site
--- a/assets/webinoly/plugins/site
+++ b/assets/webinoly/plugins/site
@@ -3,7 +3,7 @@
 # Site Manager Plugin (Create, delete and de/activate)
 # Syntax: site <domain> <option> <argument>
 # Options: -html, -php, -mysql, -wp, -parked, -proxy, -empty, -on, -off, -delete, -delete-all, -list, -cache, -ssl, -force-redirect, -yoast-sitemap, -multisite-convert, -clone-from, -replace-content, -redirection, -forward, -info, -env
-# Arguments: -cache, -root, -root-path, -subdomain, -ignore-ssl, -wildcard, -raw, -external-db, -revoke, -ssl-crt, -ssl-key, -ssl-ocsp, -subfolder, -from, -to, -http-code, -regex, -manual, -overwrite, -wp-cache-plugins, -dedicated-reverse-proxy, -must-staple, -times, -skip-cache, -skip-cookie-cache, -query-string-cache, -query-string-never-cache, -reset
+# Arguments: -cache, -root, -root-path, -subdomain, -ignore-ssl, -wildcard, -raw, -external-db, -revoke, -ssl-crt, -ssl-key, -ssl-ocsp, -subfolder, -from, -to, -http-code, -regex, -manual, -overwrite, -wp-cache-plugins, -dedicated-reverse-proxy, -must-staple, -cache-valid, -skip-cache, -skip-cookie-cache, -query-string-cache, -query-string-never-cache, -query-string-cache-default, -reset
 
 # shopt is necessary for this kind !(html|22222) of patterns
 shopt -s extglob
@@ -12,7 +12,7 @@ source /opt/webinoly/lib/general
 source /opt/webinoly/lib/sites
 check_for_parameters $@
 api-events_update sis
-check_for_nginx -ask
+[[ -z $empty_param && -z $h && -z $H && -z $help ]] && check_for_nginx -ask
 
 
 # Evaluate if site to create is WP ( 0 = noWP, 1 = WP ask, 2 = WP default, 3 = WP unattended, 4 = MySQL default, 5 = MySQL unattended )
@@ -346,10 +346,13 @@ elif [[ -n $ssl ]]; then
 			elif [[ ! -d /etc/letsencrypt/live/$add_to_wildcard ]]; then
 				echo "${red}[ERROR] Wildcard Cert not found!${end}"
 				exit 1
+			elif [[ $(is_ssl_wildcard $add_to_wildcard) != "true" ]]; then
+				echo "${red}[ERROR] Seem like you are trying to use a cert that is not Wildcard!${end}"
+				exit 1
 			elif [[ $domain == *."$add_to_wildcard" ]]; then
 				ssl_nginx
 				[[ $(is_wp $domain) == "true" ]] && edit_wp_db_url $domain "https://${domain}"
-				echo "${gre}Your site ${blu}- $domain -${gre} have been successfully added to the ${blu}- $add_to_wildcard -${gre} wildcard cert.${end}"
+				echo "${gre}Your site${blu} $domain ${gre}have been successfully added to the${blu} $add_to_wildcard ${gre}wildcard cert.${end}"
 			else
 				echo "${red}[ERROR] Seems like your site is not a valid subdomain!${end}"
 				exit 1
@@ -453,6 +456,8 @@ elif [[ -n $info && -f /etc/nginx/sites-available/$domain ]]; then
 	nginx_not="true" # Nginx-Reload not-needed.
 	
 
+elif [[ -n $help || -n $h || -n $H || $empty_param == "true" ]]; then
+	help_message
 # Catch ERROR 
 elif [[ -n $domain && ! -f /etc/nginx/sites-available/$domain ]]; then
 	echo "${red}[ERROR] Site${blu} $domain ${red}doesn't exists, please enter a valid domain name!${end}"
