Current state

diff --git a/assets/webinoly/lib/sites b/assets/webinoly/lib/sites
--- a/assets/webinoly/lib/sites
+++ b/assets/webinoly/lib/sites
@@ -152,17 +152,21 @@ wpinstall() {
 	
 	# Download WP (latest version)
 	if [[ $type == [123] ]]; then
-		echo "${dim}Downloading WordPress...${end}${blu}"
-		sudo wget --timeout=15 -t 1 -qrO /var/www/$domain/htdocs/wp.tar.gz https://wordpress.org/latest.tar.gz
-		if [[ ! -s /var/www/$domain/htdocs/wp.tar.gz ]]; then
-			echo "${red}[ERROR] Downloading WordPress failed!${end}"
-			exit 1
-		fi
-		
-		sudo tar -xf /var/www/$domain/htdocs/wp.tar.gz -C /var/www/$domain/
+
+		if [[ ! -s /var/www/wp.tar.gz ]]; then
+      echo "${dim}Downloading WordPress...${end}${blu}"
+      sudo wget --timeout=15 -t 1 -qrO /var/www/wp.tar.gz https://wordpress.org/latest.tar.gz
+
+      if [[ ! -s /var/www/wp.tar.gz ]]; then
+        echo "${red}[ERROR] Downloading WordPress failed!${end}"
+        exit 1
+      fi
+    fi
+
+		sudo tar -xf /var/www/wp.tar.gz -C /var/www/$domain/
 		sudo mv /var/www/$domain/wordpress/* /var/www/$domain/htdocs$subfolder/
 		sudo rm -rf /var/www/$domain/wordpress
-		sudo rm /var/www/$domain/htdocs/wp.tar.gz
+		# sudo rm /var/www/$domain/htdocs/wp.tar.gz
 	fi
 	
 	# Generate and auto-fill wp-config.php and also create database
