Update to Webinoly 1.16.7

diff --git a/assets/webinoly/lib/webin b/assets/webinoly/lib/webin
--- a/assets/webinoly/lib/webin
+++ b/assets/webinoly/lib/webin
@@ -74,11 +74,17 @@ system_info() {
 	echo "${blu}${bol}[MYSQL]${end}"
 	if [[ $(conf_read mysql) == "true" ]]; then
 		
-		[[ $(conf_read mysql-tool-pma) == "true" ]] && local pmaver=$(grep -E "public const VERSION = '[0-9\.]+'.*;" /var/www/$(conf_read tools-port)/htdocs/pma/libraries/classes/Version.php | cut -f 2 -d "'") || local pmaver="Not installed!"
+		# Check if file exist because in legacy it doesn't!
+		if [[ $(conf_read mysql-tool-pma) == "true" && -f /var/www/$(conf_read tools-port)/htdocs/pma/libraries/classes/Version.php ]]; then
+			local pmaver=$(grep -E "public const VERSION = '[0-9\.]+'.*;" /var/www/$(conf_read tools-port)/htdocs/pma/libraries/classes/Version.php | cut -f 2 -d "'")
 		
 		# Legacy support: before v5.1.0 (Feb 23, 2021) version is found here:
-		[[ $(conf_read mysql-tool-pma) == "true" && -z $pmaver ]] && local pmaver=$(grep -e "\$this->set('PMA_VERSION',.*'[0-9\.]*');" /var/www/$(conf_read tools-port)/htdocs/pma/libraries/classes/Config.php | cut -f 4 -d "'")
-
+		elif [[ $(conf_read mysql-tool-pma) == "true" ]]; then
+			local pmaver=$(grep -e "\$this->set('PMA_VERSION',.*'[0-9\.]*');" /var/www/$(conf_read tools-port)/htdocs/pma/libraries/classes/Config.php | cut -f 4 -d "'")
+		
+		elif [[ $(conf_read mysql-tool-pma) != "true" ]]; then
+			local pmaver="Not installed!"
+		fi
 		
 		echo "${blu}Info:${end}${dim} $(sudo mysql --version) ${end}"
 		echo "${blu}phpMyAdmin:${end}${dim} $pmaver ${end}"
@@ -210,6 +216,11 @@ smtp_setup() {
 
 
 mysql_change_password() {
+	if ! sudo mysql --connect-timeout=10 --user=admin -p$ADMIN_PASS -e "quit" 2>/dev/null; then
+		echo "${red}[ERROR] MySQL Connection to localhost failed! ${dim}(admin)${end}"
+		exit 1
+	fi
+	
 	if [[ $mysql_password == true ]]; then
 		echo ""
 		read -p "${blu}MySQL User: ${end}" user
@@ -234,10 +245,13 @@ mysql_change_password() {
 			exit 1
 	fi
 	
-	sudo mysql --connect-timeout=10 --user=admin -p$ADMIN_PASS -e "ALTER USER '${user}'@'localhost' IDENTIFIED BY '${pass}';FLUSH PRIVILEGES;"
+	# First get the User host: 'localhost' or '%'
+	local userhost=$(sudo mysql -ss --connect-timeout=10 --user=admin -p$ADMIN_PASS -e "SELECT Host FROM mysql.user WHERE User='${user}' LIMIT 1;")
+	
+	sudo mysql --connect-timeout=10 --user=admin -p$ADMIN_PASS -e "ALTER USER '${user}'@'${userhost}' IDENTIFIED BY '${pass}';FLUSH PRIVILEGES;"
 	if [[ $? == 0 ]]; then
 		[[ $user =~ ^(root|admin)$ ]] && conf_write mysql-${user} $( echo $pass | openssl enc -a -salt )
-		echo "${gre}MySQL Password successfully changed!${end}"
+		echo "${gre}MySQL Password successfully changed! ${dim}('${user}'@'${userhost}')${end}"
 	else
 		echo "${red}[ERROR] Unexpected error!${end}"
 		exit 1
@@ -280,6 +294,8 @@ mysql_public_access() {
 			read -p "${blu}Master User Password: ${end}" pass
 		fi
 		
+		[[ ${pass,,} == "random" ]] && local pass=`pwgen -s -1 16`
+		
 		if [[ -z $user || -z $pass || $user == *"'"* || $pass == *"'"* || ${#pass} -lt 8 ]]; then
 			echo "${red}[ERROR] Please, enter a valid username and password!"
 			echo "Password can not contain a 'single quote' and must be at least 8 characters long.${end}"
@@ -299,7 +315,7 @@ GRANT ${priv} ON *.* TO '${user}'@'%' ${grant};
 FLUSH PRIVILEGES;
 _EOF_
 
-			[[ $? == 0 ]] && echo "${gre}${dim}Master User${blu} '${user}' ${gre}successfully created!${end}" || echo "${red}[ERROR] Unexpected error!${end}"
+			[[ $? == 0 ]] && echo "${gre}${dim}Master User${blu} $user ${gre}with password ${blu}${pass}${gre} successfully created!${end}" || echo "${red}[ERROR] Unexpected error!${end}"
 		fi
 	
 	fi
@@ -358,7 +374,8 @@ webinoly_update() {
 	if [[ $? == 0 ]]; then
 		echo "${gre}Webinoly App has been updated successfully!${dim} (Updated to: v$(conf_read app-version))${end}"
 	else
-		sudo rm weby
+		# Check if exist, because it can be deleted before if an error is triggered in the installer, for instance.
+		[[ -f weby ]] && sudo rm weby
 		echo "${red}[ERROR] Update process has failed!${end}"
 		exit 1
 	fi
@@ -375,18 +392,19 @@ wp_package_update() {
 
 
 fix_permissions() {
-	sudo find /var/www ! -path "/var/www/\.*" -type d -exec chmod 755 {} \;
-	sudo find /var/www ! -path "/var/www/\.*" -type f -exec chmod 644 {} \;
+	# https://github.com/QROkes/webinoly/issues/49
+	sudo find /var/www ! -path "/var/www/\.*" -type d -print0 | sudo xargs -r -0 chmod 755
+	sudo find /var/www ! -path "/var/www/\.*" -type f -print0 | sudo xargs -r -0 chmod 644
 	
 	if [[ -d /var/www/.ssh ]]; then
-		sudo find /var/www/.ssh -type d -exec chmod 700 {} \;
-		sudo find /var/www/.ssh ! -path "/var/www/.ssh/*.pub" -type f -exec chmod 600 {} \;
-		sudo find /var/www/.ssh -path "/var/www/.ssh/*.pub" -type f -exec chmod 644 {} \;
+		sudo find /var/www/.ssh -type d -print0 | sudo xargs -r -0 chmod 700
+		sudo find /var/www/.ssh ! -path "/var/www/.ssh/*.pub" -type f -print0 | sudo xargs -r -0 chmod 600
+		sudo find /var/www/.ssh -path "/var/www/.ssh/*.pub" -type f -print0 | sudo xargs -r -0 chmod 644
 	fi
 	if [[ -d $CURRENT_HOME/.ssh ]]; then
-		sudo find $CURRENT_HOME/.ssh -type d -exec chmod 700 {} \;
-		sudo find $CURRENT_HOME/.ssh ! -path "$CURRENT_HOME/.ssh/*.pub" -type f -exec chmod 600 {} \;
-		sudo find $CURRENT_HOME/.ssh -path "$CURRENT_HOME/.ssh/*.pub" -type f -exec chmod 644 {} \;
+		sudo find $CURRENT_HOME/.ssh -type d -print0 | sudo xargs -r -0 chmod 700
+		sudo find $CURRENT_HOME/.ssh ! -path "$CURRENT_HOME/.ssh/*.pub" -type f -print0 | sudo xargs -r -0 chmod 600
+		sudo find $CURRENT_HOME/.ssh -path "$CURRENT_HOME/.ssh/*.pub" -type f -print0 | sudo xargs -r -0 chmod 644
 		sudo chown -R ${CURRENT_USER}:${CURRENT_USER} $CURRENT_HOME/.ssh
 	fi
 	
@@ -463,7 +481,7 @@ server_reset() {
 show_db_data() {
 	if [[ -n $(conf_read external-dbu) && -n $(conf_read external-dbp) ]]; then
 		local extu=$(conf_read external-dbu)
-		local extp=$( echo $(conf_read external-dbp) | openssl enc -d -a -salt )
+		local extp=$(conf_read external-dbp)
 		
 		if [[ -n $(conf_read external-dbh) && -n $(conf_read external-dbx) ]]; then
 			local exth="$(conf_read external-dbh):$(conf_read external-dbx)"
@@ -535,6 +553,7 @@ change_tools_port() {
 		fi
 		
 		conf_write tools-port $port
+		conf_write tools-port-set $port
 		echo "${gre}Port${blu} $port ${gre}has been enabled to access all your Tools! ${end}"
 	else
 		echo "${red}[ERROR] Please, enter a valid port number (1-65535)!${end}"
@@ -663,6 +682,7 @@ Match Group sftponly
 		[[ -n $falus ]] && sudo sed -i "s/$falus/$falus www-data/" /etc/ssh/sshd_config
 
 		conf_write login-www-data true
+		conf_write sftp-www-data true
 		sudo systemctl restart ssh
 		echo "${gre}SFTP access for www-data user has been successfuly enabled! ${end}"
 	
@@ -683,6 +703,7 @@ Match Group sftponly
 		fi
 
 		conf_write login-www-data purged
+		conf_write sftp-www-data purged
 		sudo systemctl restart ssh
 		echo "${gre}SFTP access for www-data user has been successfuly disabled! ${end}"
 	else
@@ -903,6 +924,7 @@ set_default_nginx_response() {
 			sudo cat /opt/webinoly/templates/source/default >| /etc/nginx/sites-available/default
 			remove_domain_default_site
 			conf_write default-site default
+			conf_write default-response default
 			echo "${gre}Default Nginx was successfully assigned as default site!${end}"
 		else
 			echo "${red}[ERROR] Nginx Default file backup not found! ${end}"
@@ -913,6 +935,7 @@ set_default_nginx_response() {
 		remove_domain_default_site
 		create_blackhole_cert
 		conf_write default-site blackhole
+		conf_write default-response blackhole
 		echo "${gre}Blackhole Nginx site was successfully assigned as default site!${end}"
 	else
 		# Domain option
@@ -935,6 +958,7 @@ set_default_nginx_response() {
 			
 			sudo rm -rf /etc/nginx/sites-enabled/default
 			conf_write default-site $default_site
+			conf_write default-response $default_site
 			echo "${gre}Site${blu} ${default_site} ${gre}was successfully assigned as default site!${end}"
 		else
 			[[ -f /etc/nginx/sites-available/$default_site ]] && echo "${red}Site found but is disabled.${end}"
@@ -1017,55 +1041,53 @@ database_import() {
 }
 
 
-ext_db_save() {
-	if [[ $external_db_save == "purge" || -n $purge ]]; then
-		conf_delete external-dbu -commented
-		conf_delete external-dbp -commented
-		conf_delete external-dbh -commented
-		conf_delete external-dbx -commented
-		echo "${gre}External DB data successfully removed!${end}"
+http_header_custom() {
+	if ! [[ $custom_headers =~ ^(reload|remove)$ ]]; then
+		echo "${red}[ERROR] Please, enter a valid option Custom Headers!${end}"
+		exit 1
+	fi
+	
+	if [[ $(conf_read nginx) == "true" ]]; then
+		sudo sed -i '/WebinolyCustomHeaders/,/WebinolyCustomHeadersEnd/{/.*/d}' /etc/nginx/common/headers-http.conf
+		sudo sed -i '/WebinolyCustomHeaders/,/WebinolyCustomHeadersEnd/{/.*/d}' /etc/nginx/common/headers-https.conf
+		sudo sed -i '/WebinolyCustomHeaders/,/WebinolyCustomHeadersEnd/{/.*/d}' /etc/nginx/common/headers-html.conf
+	fi
+	
+	if [[ $custom_headers == "reload" && $(conf_read nginx) == "true" ]]; then
+		if [[ -s /opt/webinoly/templates/source/custom_header_http_webinoly.data ]]; then
+			local http="$(sudo grep -E "^add_header .*;$" /opt/webinoly/templates/source/custom_header_http_webinoly.data)"
+			if [[ -n $http ]]; then
+				echo "# WebinolyCustomHeaders
+$http
+# WebinolyCustomHeadersEnd" >> /etc/nginx/common/headers-http.conf
+			fi
+		fi
+		
+		if [[ -s /opt/webinoly/templates/source/custom_header_https_webinoly.data ]]; then
+			local https="$(sudo grep -E "^add_header .*;$" /opt/webinoly/templates/source/custom_header_https_webinoly.data)"
+			if [[ -n $https ]]; then
+				echo "# WebinolyCustomHeaders
+$https
+# WebinolyCustomHeadersEnd" >> /etc/nginx/common/headers-https.conf
+			fi
+		fi
+		
+		if [[ -s /opt/webinoly/templates/source/custom_header_html_webinoly.data ]]; then
+			local html="$(sudo grep -E "^add_header .*;$" /opt/webinoly/templates/source/custom_header_html_webinoly.data)"
+			if [[ -n $html ]]; then
+				echo "# WebinolyCustomHeaders
+$html
+# WebinolyCustomHeadersEnd" >> /etc/nginx/common/headers-html.conf
+			fi
+		fi
+		
+		conf_write header-custom true
+		echo "${gre}Custom Headers successfully configured!${end}"
+	elif [[ $custom_headers == "reload" ]]; then
+		conf_write header-custom true
+		echo "${gre}Custom Headers successfully configured and it will be used next time NGINX is installed!${end}"
 	else
-		if [[ $external_db_save == "true" ]]; then
-			read -p "${blu} Host: ${end}" host
-			read -p "${blu} User: ${end}" user
-			read -p "${blu} Password: ${end}" pass
-			
-			if [[ -z $host || -z $user || -z $pass || $user =~ [:]+ || $pass =~ [:]+ ]]; then
-				echo "${red}[ERROR] Invalid data for External Database!${end}"
-				exit 1
-			fi
-		else
-			# Prevent errors
-			if [[ ${#external_db_save} -lt 2 ]]; then
-				echo "${red}[ERROR] Invalid data for External Database!${end}"
-				exit 1
-			fi
-			
-			local dbdata=${external_db_save:1:-1}
-			local user=$(echo "${dbdata}" | cut -d',' -f 1 -s)
-			local pass=$(echo "${dbdata}" | cut -d',' -f 2 -s)
-			local host=$(echo "${dbdata}" | cut -d',' -f 3 -s)
-			
-			if [[ $(echo "${external_db_save}" | cut -c-1) != "[" || $(echo "${external_db_save}" | rev | cut -c-1) != "]" || -z $host || -z $user || -z $pass || $user =~ [:]+ || $pass =~ [:]+ ]]; then
-				echo "${red}[ERROR] Invalid data for External Database!${end}"
-				exit 1
-			fi
-		fi
-		
-		
-		is_url $host -split
-		if [[ -z $url_path && $(is_url $host) =~ ^(http|https|ip|true)$ && -n $url_host && -n $url_port ]]; then
-			conf_write external-dbh $url_host
-			conf_write external-dbx $url_port
-		else
-			echo "${red}[ERROR] Invalid database host/port!${end}"
-			exit 1
-		fi
-		
-		conf_write external-dbu $user
-		conf_write external-dbp $( echo $pass | openssl enc -a -salt )
-		
-		echo "${gre}External DB data successfully saved!${end}"
+		conf_write header-custom false
+		echo "${gre}Custom Headers successfully removed!${end}"
 	fi
 }
-
diff --git a/assets/webinoly/usr/site b/assets/webinoly/usr/site
--- a/assets/webinoly/usr/site
+++ b/assets/webinoly/usr/site
@@ -26,7 +26,7 @@ if [[ -n $wp || -n $mysql ]]; then
 
 	# Check for saved DB external data
 	if [[ ( $wp == "true" || $mysql == "true" ) && -n $(conf_read external-dbh) && -n $(conf_read external-dbu) && -n $(conf_read external-dbp) ]]; then
-		[[ -n $domain ]] && dona=$(echo $domain | sed "s/[^0-9A-Za-z]/_/g") || dona="Webinoly_$(pwgen -s -1)"
+		[[ -n $domain ]] && dona=$(echo $domain$subfolder | sed "s/[^0-9A-Za-z]/_/g") || dona="Webinoly_$(pwgen -s -1)"
 		
 		if [[ -n $(conf_read external-dbh) && -n $(conf_read external-dbx) ]]; then
 			exth="$(conf_read external-dbh):$(conf_read external-dbx)"
@@ -34,9 +34,8 @@ if [[ -n $wp || -n $mysql ]]; then
 			exth=$(conf_read external-dbh)
 		fi
 		
-		extp=$( echo $(conf_read external-dbp) | openssl enc -d -a -salt )
-		[[ $wp == "true" ]] && wp="[true,true,${exth},${dona},${dona},random,wp_,$(conf_read external-dbu),${extp}]"
-		[[ $mysql == "true" ]] && mysql="[${exth},${dona},${dona},random,$(conf_read external-dbu),${extp}]"
+		[[ $wp == "true" ]] && wp="[true,true,${exth},${dona},${dona},random,wp_,$(conf_read external-dbu),$(conf_read external-dbp)]"
+		[[ $mysql == "true" ]] && mysql="[${exth},${dona},${dona},random,$(conf_read external-dbu),$(conf_read external-dbp)]"
 		echo "${blu}${dim}External DB credentials found!${end}"
 	fi
 
@@ -104,7 +103,8 @@ if [[ -n $subfolder && ! ( $subfolder =~ ^\/([A-Za-z0-9_\/\-]+)?[^\/]$ ) ]]; the
 elif [[ -n $subfolder && -z $delete && -z $cache && -z $multisite_convert && -z $clone_from && -z $replace_content && -z $wp && -z $html && -z $php && -z $mysql && -z $proxy && -z $env && -z $info ]]; then
 	echo "${red}[ERROR] Subfolder option not supported!${end}"
 	exit 1
-elif [[ -n $subfolder && ( $cache == "on" || -n $multisite_convert || -n $replace_content ) && $(is_subfolder $domain $subfolder) != "wp" ]]; then
+# Clone-from empty is here to allow -cache=on when cloning a site
+elif [[ -n $subfolder && ( $cache == "on" || -n $multisite_convert || -n $replace_content ) && $(is_subfolder $domain $subfolder) != "wp" && -z $clone_from ]]; then
 	echo "${red}[ERROR] Subfolder not found or is not a WP site!${end}"
 	exit 1
 else
@@ -215,7 +215,12 @@ elif [[ -n $multisite_convert && -f /etc/nginx/sites-available/$domain ]]; then
 	if [[ $(is_wp $domain $subfolder) == "false" ]]; then
 		echo "${red}[ERROR] Site${blu} $domain$subfolder ${red}is not a WP site!${end}"
 		exit 1
-	elif [[ $(is_wp_installed $domain $subfolder) != "true" ]]; then
+	fi
+	
+	# We need to call this function in the parent shell to preserve variables and avoid asking two or more times for the same values in case of external db.
+	wp_conf_retrieve $domain true false $subfolder 	
+	
+	if [[ $(is_wp_installed $domain $subfolder) != "true" ]]; then
 		echo "${red}[ERROR] WordPress site${blu} $domain$subfolder ${red}is empty and still not configured!${end}"
 		exit 1
 	elif [[ $(is_parked $domain) == "true" ]]; then
@@ -276,24 +281,6 @@ elif [[ -n $redirection && -f /etc/nginx/sites-available/$domain ]]; then
 	redirection_manager
 
 
-# FastCGI Cache
-elif [[ -n $cache && -f /etc/nginx/sites-available/$domain ]]; then
-	wp_cache
-
-	
-# Delete site	
-elif [[ -n $delete && -f /etc/nginx/sites-available/$domain ]]; then
-	api-events_update si6
-	if [[ $domain == "default" || $domain == $(conf_read tools-port) ]]; then
-		echo "${red}[ERROR] System sites can not be removed!${end}"
-		exit 1
-	elif [[ -n $subfolder ]]; then
-		deletesite_subfolder
-	else
-		deletesite
-	fi
-
-
 # SSL (Letsencrypt)
 elif [[ -n $ssl ]]; then
 	if [[ $ssl == "renew" && -z $domain ]]; then
@@ -335,7 +322,10 @@ elif [[ -n $ssl ]]; then
 				exit 1
 			elif [[ $domain == *."$add_to_wildcard" ]]; then
 				ssl_nginx
-				[[ $(is_wp $domain) == "true" ]] && edit_wp_db_url $domain "https://${domain}"
+				
+				# No need of force-redirect check because this site is always subdomain and subdomains are not supported in force-redirect.
+				[[ $(is_wp $domain) == "true" ]] && wp_db_update $domain "https://${domain}"
+				
 				echo "${gre}Your site${blu} $domain ${gre}have been successfully added to the${blu} $add_to_wildcard ${gre}wildcard cert.${end}"
 			else
 				echo "${red}[ERROR] Seems like your site is not a valid subdomain!${end}"
@@ -396,6 +386,9 @@ elif [[ -n $clone_from ]]; then
 		elif [[ $(is_wp_installed $clone_from $subfolder) != "true" ]]; then
 			echo "${dim}[INFO] WordPress is empty and still not configured in ${clone_from}${subfolder} site!${end}"
 		fi
+	elif [[ -n $subfolder && $(is_subfolder $clone_from $subfolder) == "false" ]]; then
+		echo "${red}[ERROR] Subfolder not found!${end}"
+		exit 1
 	fi
 	
 	cloning_site
@@ -406,15 +399,42 @@ elif [[ -n $replace_content && -f /etc/nginx/sites-available/$domain ]]; then
 	if [[ $(is_wp $domain $subfolder) != "true" ]]; then
 		echo "${red}[ERROR] Site${blu} $domain$subfolder ${red}is not a WordPress site!${end}"
 		exit 1
+	fi
+	
+	#We need to call this function in the parent shell to preserve variables and avoid asking two times for the same values in case of external db.
+	wp_conf_retrieve $domain true true $subfolder
+	
+	if [[ $(is_wp_installed $domain $subfolder) != "true" ]]; then
+		echo "${red}[ERROR] WordPress is empty and still not configured in ${domain}${subfolder} site!${end}"
+		exit 1
 	else
 		wp_replace_content
 	fi
 
 
-# WordPress Environment Type
+# WordPress Environment Type (should be here after cloning site for precedence)
 elif [[ -n $env && -f /etc/nginx/sites-available/$domain ]]; then
 	wp_env_type
 	nginx_not="true" # Nginx-Reload not-needed.
+# ENV should be always before cache for precedence
+
+
+# FastCGI Cache
+elif [[ -n $cache && -f /etc/nginx/sites-available/$domain ]]; then
+	wp_cache
+
+
+# Delete site (should be here after cache for precedence)
+elif [[ -n $delete && -f /etc/nginx/sites-available/$domain ]]; then
+	api-events_update si6
+	if [[ $domain == "default" || $domain == $(conf_read tools-port) ]]; then
+		echo "${red}[ERROR] System sites can not be removed!${end}"
+		exit 1
+	elif [[ -n $subfolder ]]; then
+		deletesite_subfolder
+	else
+		deletesite
+	fi
 	
 
 # List Sites
diff --git a/assets/webinoly/weby b/assets/webinoly/weby
--- a/assets/webinoly/weby
+++ b/assets/webinoly/weby
@@ -4,18 +4,10 @@
 # Check OS support
 distr=`echo $(lsb_release -i | cut -d':' -f 2)`
 osver=`echo $(lsb_release -c | cut -d':' -f 2)`
-if ! [[ $distr == "Ubuntu" && $osver =~ ^(bionic|focal)$ ]]; then
+if ! [[ $distr == "Ubuntu" && $osver =~ ^(bionic|focal|jammy)$ ]]; then
 	echo "$(tput setaf 1)"
-	echo "****************************************************************************"
-	echo "****  This OS is not supported by Webinoly and could not work properly  ****"
-	echo "****************************************************************************"
+	echo "[ERROR] This OS is not supported by Webinoly and could not work properly. $(tput dim)(${distr} '${osver}')"
 	echo "$(tput sgr0)"
-	read -p "Press [Enter] key to Continue or [Ctrl+C] to Cancel..."
-fi
-
-# Check for BASH Shell
-if [[ -z $(grep -E "^${SUDO_USER:-${USER}}\:.*\/bash.*$" /etc/passwd) ]]; then
-	echo "$(tput setaf 1)BASH Shell is required!$(tput sgr0)"
 	sudo rm weby
 	exit 1
 fi
@@ -192,7 +184,7 @@ if [[ -z $(conf_read stack-build-error-flag) ]]; then
 
 	if [[ -z $update ]]; then
 		echo ""
-		echo "${blu}${bol}Don't like our defaults? Every part of Webinoly is overrideable!${end}"
+		echo "${blu}${bol}Don't like our defaults? Every part of Webinoly is overridable!${end}"
 		echo "${blu}- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - "
 		echo "${blu}Please, read the documentation:${end}${dim} https://webinoly.com/documentation/${end}"
 		echo "${blu}Be sure your firewall ports are correctly set:${end}${dim} https://webinoly.com/install/${end}"
