Update to Webinoly 1.14.0

diff --git a/assets/webinoly/lib/webin b/assets/webinoly/lib/webin
--- a/assets/webinoly/lib/webin
+++ b/assets/webinoly/lib/webin
@@ -150,10 +150,6 @@ webinoly_verify() {
 			echo "[ERROR] File: /etc/nginx/nginx.conf not found!"
 			error="1"
 		fi
-		if [[ ! -f /etc/nginx/fastcgi.conf ]]; then
-			echo "[ERROR] File: /etc/nginx/fastcgi.conf not found!"
-			error="1"
-		fi
 	fi
 	if [[ $(conf_read nginx) != "true" ]]; then
 		if [[ -f /etc/nginx/nginx.conf ]]; then
@@ -351,11 +347,7 @@ webinoly_verify() {
 			echo "[ERROR] File: /usr/bin/duply not found!"
 			error="1"
 		fi
-		if [[ ! -L /usr/bin/letsencrypt ]]; then
-			echo "[ERROR] File: /usr/bin/letsencrypt not found!"
-			error="1"
-		fi
-		if [[ ! -f /usr/bin/certbot ]]; then
+		if [[ ! -L /usr/bin/certbot ]]; then
 			echo "[ERROR] File: /usr/bin/certbot not found!"
 			error="1"
 		fi
@@ -765,14 +757,16 @@ webinoly_update() {
 
 server_reset() {
 	# Regenerate NGINX conf files
-	if [[ $(conf_read nginx-optim) == "true" && $server_reset =~ ^(nginx|all)$ ]]; then
+	if [[ $(conf_read nginx-optim) == "true" && $server_reset =~ ^(nginx|all)$ ]]; then		
+		# Backup files will be restored in nginx_optim function
 		[[ -f /etc/nginx/conf.d/blockips.conf ]] && sudo cp -p /etc/nginx/conf.d/blockips.conf /tmp/webinoly_blockips_backup
+		[[ -f /etc/nginx/conf.d/webinoly.conf ]] && sudo cp -p /etc/nginx/conf.d/webinoly.conf /tmp/webinoly_backup
+		
 		sudo sed -i '/WebinolyCustom/,/WebinolyCustomEnd/{/.*/d}' /etc/nginx/fastcgi_params
 		sudo rm -rf /etc/nginx/common
 		sudo rm -rf /etc/nginx/conf.d/*
 		linux_purge
 		nginx_optim
-		[[ -f /tmp/webinoly_blockips_backup ]] && sudo mv /tmp/webinoly_blockips_backup /etc/nginx/conf.d/blockips.conf
 		
 		# Fix permissions
 		sudo find /var/www -type d -exec chmod 755 {} \;
@@ -1046,76 +1040,6 @@ Match Group sftponly
 }
 
 
-config_fastcgi_cache() {
-	if [[ $(conf_read nginx) == "true" ]]; then	
-		hitline=$( grep -F "fastcgi_cache_valid 200" /etc/nginx/conf.d/fastcgi.conf )
-		hitval=$(echo "${hitline//;}" | rev | cut -d' ' -f 1 | rev)
-		inaline=$( grep -F "fastcgi_cache_path" /etc/nginx/conf.d/fastcgi.conf )
-		inactive=$(echo "${inaline//;}" | rev | cut -d' ' -f 1 | rev)
-		inaval=$(echo "${inactive}" | cut -d'=' -f 2)
-		maxsize=$(echo "${inaline}" | rev | cut -d' ' -f 2 | rev)
-		othline=$( grep -F "fastcgi_cache_valid 301 302 303 307 308 404 410 451" /etc/nginx/conf.d/fastcgi.conf )
-		othval=$(echo "${othline//;}" | rev | cut -d' ' -f 1 | rev)
-	elif [[ -n $(conf_read fastcgi-conf) ]]; then
-		hitval=$( echo $(conf_read fastcgi-conf) | cut -d',' -f 1 -s )
-		inaval=$( echo $(conf_read fastcgi-conf) | cut -d',' -f 2 -s )
-		othval=$( echo $(conf_read fastcgi-conf) | cut -d',' -f 3 -s )
-	else
-		hitval="Not yet defined"
-		inaval="Not yet defined"
-		othval="Not yet defined"
-	fi
-
-	
-	if [[ $config_cache == true ]]; then
-		echo "${gre}"
-		echo "**********************************************************************"
-		echo "*************     Set FastCGI Cache new time values     **************"
-		echo "*****  Example: 30d = 30days  |  3h = 3hours  |  5m = 5minutes  ******"
-		echo "**********************************************************************"
-		echo "${blu}"
-		echo "FastCGI Cache Valid for Pages (HttpCode: 200) actual value is: $hitval"
-		read -p "   Set new value: " hit
-		hit=${hit:-$hitval}
-		echo ""
-		echo "Purge Cache for inactive pages actual value is: $inaval"
-		read -p "   Set new value: " ina
-		ina=${ina:-$inaval}
-		echo ""
-		echo "FastCGI Cache Valid for Errors and Redirections (301 302 303 307 308 404 410 451) actual value is: $othval"
-		read -p "   Set new value: " oth
-		oth=${oth:-$othval}
-		echo ""
-	elif [[ $(echo "${config_cache}" | cut -c-1) == "[" && $(echo "${config_cache}" | rev | cut -c-1) == "]" ]]; then
-		custombegin=$(echo "${config_cache}" | cut -c-1)
-		customlast=$(echo "${config_cache}" | rev | cut -c-1)
-		
-		# No need for check var lenght to prevent errors, the previous condition is enough in this case.
-		cachedata=${config_cache:1:-1}
-			
-		hit=$(echo "${cachedata}" | cut -d',' -f 1 )
-		ina=$(echo "${cachedata}" | cut -d',' -f 2 )
-		oth=$(echo "${cachedata}" | cut -d',' -f 3 )
-	else
-		echo "${red}[ERROR] Please enter a valid value!${end}"
-		exit 1
-	fi
-	
-	if [[ "$hit" =~ ^[0-9]+[smhdwMy]$ && "$ina" =~ ^[0-9]+[smhdwMy]$ && "$oth" =~ ^[0-9]+[smhdwMy]$ ]]; then
-		if [[ $(conf_read nginx) == "true" ]]; then	
-			sudo sed -i "/fastcgi_cache_valid 200/c \fastcgi_cache_valid 200 ${hit};" /etc/nginx/conf.d/fastcgi.conf
-			sudo sed -i "/fastcgi_cache_valid 301 302 /c \fastcgi_cache_valid 301 302 303 307 308 404 410 451 ${oth};" /etc/nginx/conf.d/fastcgi.conf
-			sudo sed -i "/fastcgi_cache_path/c \fastcgi_cache_path \/run\/nginx-cache levels=1:2 keys_zone=WORDPRESS:50m ${maxsize} inactive=${ina};" /etc/nginx/conf.d/fastcgi.conf
-		fi
-		conf_write fastcgi-conf ${hit},${ina},${oth}
-		echo "${gre}FastCGI Cache values has been successfully updated!${end}"
-	else
-		echo "${red}[ERROR] Invalid values!${end}"
-		exit 1
-	fi
-}
-
-
 webinoly_uninstall() {
 	echo "${red}"
 	echo "You are about to completely remove Webinoly App from your server!!"
@@ -1220,6 +1144,18 @@ clear_caches() {
 			echo "${gre}- FastCgi Cache has been successfully cleared!${end}"
 		else	
 			echo "${red}[ERROR] We can not clear FastCGI Cache because NGINX is not installed!${end}"
+			err_cont=true
+		fi
+	fi
+	if [[ -f /etc/nginx/sites-available/$clear_cache ]]; then
+		if [[ $(conf_read nginx) == "true" && $(is_cache $clear_cache $subfolder) =~ ^(custom|proxy)$ ]]; then
+			sudo rm -Rf /run/nginx-cache/$(echo $domain | sed 's/[^0-9A-Za-z]/_/g')$(echo $subfolder | sed "s/\//_/g")
+			echo "${gre}Custom Nginx Cache for${blu} ${clear_cache}${subfolder} ${gre}has been successfully cleared!${end}"
+		elif ! [[ $(is_cache $clear_cache $subfolder) =~ ^(custom|proxy)$ ]]; then
+			echo "${red}[ERROR] Custom Cache is not enabled for this site!${end}"
+			err_cont=true
+		elif [[ $(conf_read nginx) != "true" ]]; then
+			echo "${red}[ERROR] We can not clear Nginx Cache because NGINX is not installed!${end}"
 			err_cont=true
 		fi
 	fi
@@ -1922,173 +1858,55 @@ http_header_csp() {
 }
 
 
-custom_cache_global() {
-	if [[ -n $list ]]; then
-		[[ -n $raw || $list == "raw" ]] && echo "" || echo "${gre}"
-		
-		if [[ -f /etc/nginx/apps.d/global_custom_cache.conf ]]; then
-			[[ -n $query_string_never_cache ]] && local id="NeverCacheQueryString"
-			[[ -n $query_string_cache ]] && local id="CacheQueryString"
-			[[ -n $skip_cache ]] && local id="CacheSkipURL"
-			
-			local isem=$(sudo sed -n "/# Value: /{h;d;}; H; /# $id/{x;p;}" /etc/nginx/apps.d/global_custom_cache.conf)
-			
-			if [[ -n $raw || $list == "raw" ]]; then
-				sudo sed -n "/# Value: /{h;d;}; H; /# $id/{x;p;}" /etc/nginx/apps.d/global_custom_cache.conf | sed -n '/# Value:/p' | sed 's/# Value: //g'
-			else
-				sudo sed -n "/# Value: /{h;d;}; H; /# $id/{x;p;}" /etc/nginx/apps.d/global_custom_cache.conf | sed -n '/# Value:/p' | sed 's/# Value: /+ /g'
-			fi
-		fi
-		[[ -z $isem && -z $raw && $list != "raw" ]] && echo "${blu}[Empty] No Cache Rules were found!${end}"
-	
-		[[ -n $raw || $list == "raw" ]] && echo "" || echo "${end}"
-	elif [[ -n $delete ]]; then
-		echo ""
-		[[ $skip_cache == "true" ]] && read -p "${blu}Cache Skip URL to delete: ${end}" skip_cache
-		[[ $query_string_cache == "true" ]] && read -p "${blu}Cache Query String to delete: ${end}" query_string_cache
-		[[ $query_string_never_cache == "true" ]] && read -p "${blu}Never Cache this Query String to delete: ${end}" query_string_never_cache
-		if [[ -z $query_string_cache && -z $query_string_never_cache && -z $skip_cache ]]; then
-			echo "${red}[ERROR] Please, enter a valid value!${end}"
-			exit 1
-		fi
-		
-		if [[ -f /etc/nginx/apps.d/global_custom_cache.conf ]]; then
-			[[ -n $query_string_never_cache ]] && local value=$query_string_never_cache
-			[[ -n $query_string_cache ]] && local value=$query_string_cache
-			[[ -n $skip_cache ]] && local value=$skip_cache
-			
-			sudo sed -Ei "/^# Value: $(escaped_string $value)( .*)?$/,/^# CacheRuleEnd/{/.*/d}" /etc/nginx/apps.d/global_custom_cache.conf
-			[[ ! -s /etc/nginx/apps.d/global_custom_cache.conf ]] && sudo rm /etc/nginx/apps.d/global_custom_cache.conf
-		fi
-		echo "${gre}Redirection successfully removed!${end}"
+ext_db_save() {
+	if [[ $external_db_save == "purge" || -n $purge ]]; then
+		conf_delete external-dbu
+		conf_delete external-dbp
+		conf_delete external-dbh
+		conf_delete external-dbx
+		echo "${gre}External DB data successfully removed!${end}"
 	else
-		echo ""
-		[[ $skip_cache == "true" ]] && read -p "${blu}Cache Skip URL: ${end}" skip_cache
-		[[ $query_string_cache == "true" ]] && read -p "${blu}Cache Query String: ${end}" query_string_cache
-		[[ $query_string_never_cache == "true" ]] && read -p "${blu}Never Cache this Query String: ${end}" query_string_never_cache
-		echo ""
-		
-		if [[ -z $query_string_cache && -z $query_string_never_cache && -z $skip_cache ]]; then
-			echo "${red}[ERROR] Please, enter a valid value!${end}"
-			exit 1
-		elif [[ -n $regex && ( -n $query_string_cache || -n $query_string_never_cache ) ]]; then
-			echo "${red}[ERROR] Regex not allowed for Query-String custom rules!${end}"
-			exit 1
-		elif [[ $skip_cache == "/" && -z $regex ]]; then
-			echo "${red}[ERROR] Root folder not allowed, use regex or disable site cache!${end}"
-			exit 1
-		elif [[ -n $regex ]] && ! [[ $regex =~ ^(sensitive|insensitive)$ ]]; then
-			echo "${red}[ERROR] Invalid regex value!${end}"
-			exit 1
-		elif [[ -z $regex &&  -n $skip_cache && $(is_url_path $skip_cache) != "true" ]]; then
-			echo "${red}[ERROR] Invalid URL!${end}"
-			exit 1
-		elif [[ -z $regex && -n $query_string_cache ]] && ! [[ $query_string_cache =~ ^([\]A-Za-z0-9_\/\.:\!\*\'\[\(\)\;@\&\=\+\$\,\?#\~\%\-]+)?$ ]]; then
-			echo "${red}[ERROR] Invalid Query String!${end}"
-			exit 1
-		elif [[ -z $regex && -n $query_string_never_cache ]] && ! [[ $query_string_never_cache =~ ^([\]A-Za-z0-9_\/\.:\!\*\'\[\(\)\;@\&\=\+\$\,\?#\~\%\-]+)?$ ]]; then
-			echo "${red}[ERROR] Invalid Query String!${end}"
-			exit 1
-		fi
-		
-		if [[ ! -f /etc/nginx/apps.d/global_custom_cache.conf ]]; then
-			sudo touch /etc/nginx/apps.d/global_custom_cache.conf
-			sudo chmod 644 /etc/nginx/apps.d/global_custom_cache.conf
-			sudo chown -R root:root /etc/nginx/apps.d/global_custom_cache.conf
-		fi
-		
-		[[ -n $query_string_never_cache ]] && local value=$query_string_never_cache
-		[[ -n $query_string_cache ]] && local value=$query_string_cache
-		[[ -n $skip_cache ]] && local value=$skip_cache
-		
-		local exist=$( grep -E "^# Value: $(escaped_string $value)( .*)?$" /etc/nginx/apps.d/global_custom_cache.conf )
-		
-		if [[ -z $exist ]]; then
-			if [[ $regex == "sensitive" ]]; then
-				sign="~"
-				code="$value (Regex)"
-			elif [[ $regex == "insensitive" ]]; then
-				sign="~*"
-				code="$value (Regex)"
-			else
-				sign="="
-				code="$value"
-			fi
+		if [[ $external_db_save == "true" ]]; then
+			read -p "${blu} Host: ${end}" host
+			read -p "${blu} User: ${end}" user
+			read -p "${blu} Password: ${end}" pass
 			
-			if [[ -n $query_string_never_cache ]]; then
-				echo "# Value: $code
-# NeverCacheQueryString
-if (\$arg_${value}) {
-	set \$skip_cache 1;
-}
-# CacheRuleEnd" >> /etc/nginx/apps.d/global_custom_cache.conf
-			elif [[ -n $query_string_cache ]]; then
-				# Sed can not write when file is empty
-				[[ ! -s /etc/nginx/apps.d/global_custom_cache.conf ]] && echo ' ' >> /etc/nginx/apps.d/global_custom_cache.conf
-				sudo sed -i "1i # Value: $code\n# CacheQueryString\nif (\$arg_${value}) {\n	set \$skip_cache 0;\n}\n# CacheRuleEnd" /etc/nginx/apps.d/global_custom_cache.conf
-			elif [[ -n $skip_cache ]]; then
-				[[ ! -s /etc/nginx/apps.d/global_custom_cache.conf ]] && echo ' ' >> /etc/nginx/apps.d/global_custom_cache.conf
-				sudo sed -i "1i # Value: $code\n# CacheSkipURL\nif (\$request_uri $sign $value) {\n	set \$skip_cache 1;\n}\n# CacheRuleEnd" /etc/nginx/apps.d/global_custom_cache.conf
+			if [[ -z $host || -z $user || -z $pass || $user =~ [:]+ || $pass =~ [:]+ ]]; then
+				echo "${red}[ERROR] Invalid data for External Database!${end}"
+				exit 1
 			fi
-			
-			# Last verification
-			if ! sudo nginx -t > /dev/null 2>&1; then
-				[[ -n $query_string_never_cache ]] && sudo webinoly -query-string-never-cache=$query_string_never_cache -delete > /dev/null 2>&1
-				[[ -n $query_string_cache ]] && sudo webinoly -query-string-cache=$query_string_cache -delete > /dev/null 2>&1
-				[[ -n $skip_cache ]] && sudo webinoly -skip-cache=$skip_cache -delete > /dev/null 2>&1
-				echo "${red}[ERROR] Seems like you are using some invalid Nginx values or characters!${end}"
+		else
+			# Prevent errors
+			if [[ ${#external_db_save} -lt 2 ]]; then
+				echo "${red}[ERROR] Invalid data for External Database!${end}"
 				exit 1
 			fi
 			
-			echo "${gre}Cache rule successfully added!${end}"
+			local dbdata=${external_db_save:1:-1}
+			local user=$(echo "${dbdata}" | cut -d',' -f 1 -s)
+			local pass=$(echo "${dbdata}" | cut -d',' -f 2 -s)
+			local host=$(echo "${dbdata}" | cut -d',' -f 3 -s)
+			
+			if [[ $(echo "${external_db_save}" | cut -c-1) != "[" || $(echo "${external_db_save}" | rev | cut -c-1) != "]" || -z $host || -z $user || -z $pass || $user =~ [:]+ || $pass =~ [:]+ ]]; then
+				echo "${red}[ERROR] Invalid data for External Database!${end}"
+				exit 1
+			fi
+		fi
+		
+		
+		is_url $host -split
+		if [[ -z $url_path && $(is_url $host) =~ ^(http|https|ip|true)$ && -n $url_host && -n $url_port ]]; then
+			conf_write external-dbh $url_host
+			conf_write external-dbx $url_port
 		else
-			echo "${gre}Cache rule already exists!${end}"
-		fi
-	fi
-}
-
-
-ext_db_save() {
-	if [[ $external_db_save == "true" ]]; then
-		read -p "${blu} Host: ${end}" host
-		read -p "${blu} User: ${end}" user
-		read -p "${blu} Password: ${end}" pass
-		
-		if [[ -z $host || -z $user || -z $pass || $user =~ [:]+ || $pass =~ [:]+ ]]; then
-			echo "${red}[ERROR] Invalid data for External Database!${end}"
-			exit 1
-		fi
-	else
-		# Prevent errors
-		if [[ ${#external_db_save} -lt 2 ]]; then
-			echo "${red}[ERROR] Invalid data for External Database!${end}"
+			echo "${red}[ERROR] Invalid database host/port!${end}"
 			exit 1
 		fi
 		
-		local dbdata=${external_db_save:1:-1}
-		local user=$(echo "${dbdata}" | cut -d',' -f 1 -s)
-		local pass=$(echo "${dbdata}" | cut -d',' -f 2 -s)
-		local host=$(echo "${dbdata}" | cut -d',' -f 3 -s)
+		conf_write external-dbu $user
+		conf_write external-dbp $( echo $pass | openssl enc -a -salt )
 		
-		if [[ $(echo "${external_db_save}" | cut -c-1) != "[" || $(echo "${external_db_save}" | rev | cut -c-1) != "]" || -z $host || -z $user || -z $pass || $user =~ [:]+ || $pass =~ [:]+ ]]; then
-			echo "${red}[ERROR] Invalid data for External Database!${end}"
-			exit 1
-		fi
+		echo "${gre}External DB data successfully saved!${end}"
 	fi
-	
-	
-	is_url $host -split
-	if [[ -z $url_path && $(is_url $host) =~ ^(http|https|ip|true)$ && -n $url_host && -n $url_port ]]; then
-		conf_write external-dbh $url_host
-		conf_write external-dbx $url_port
-	else
-		echo "${red}[ERROR] Invalid database host/port!${end}"
-		exit 1
-	fi
-	
-	conf_write external-dbu $user
-	conf_write external-dbp $( echo $pass | openssl enc -a -salt )
-	
-	echo "${gre}External DB data successfully saved!${end}"
 }
 
diff --git a/assets/webinoly/plugins/site b/assets/webinoly/plugins/site
--- a/assets/webinoly/plugins/site
+++ b/assets/webinoly/plugins/site
@@ -2,8 +2,8 @@
 
 # Site Manager Plugin (Create, delete and de/activate)
 # Syntax: site <domain> <option> <argument>
-# Options: -html, -php, -mysql, -wp, -parked, -proxy, -on, -off, -delete, -delete-all, -list, -cache, -ssl, -force-redirect, -yoast-sitemap, -multisite-convert, -clone-from, -replace-content, -redirection, -forward, -info, -env
-# Arguments: -cache, -root, -root-path, -subdomain, -ignore-ssl, -wildcard, -raw, -external-db, -revoke, -ssl-crt, -ssl-key, -ssl-ocsp, -subfolder, -from, -to, -http-code, -regex, -manual, -overwrite, -wp-cache-plugins
+# Options: -html, -php, -mysql, -wp, -parked, -proxy, -empty, -on, -off, -delete, -delete-all, -list, -cache, -ssl, -force-redirect, -yoast-sitemap, -multisite-convert, -clone-from, -replace-content, -redirection, -forward, -info, -env
+# Arguments: -cache, -root, -root-path, -subdomain, -ignore-ssl, -wildcard, -raw, -external-db, -revoke, -ssl-crt, -ssl-key, -ssl-ocsp, -subfolder, -from, -to, -http-code, -regex, -manual, -overwrite, -wp-cache-plugins, -dedicated-reverse-proxy, -must-staple, -times, -skip-cache, -skip-cookie-cache, -query-string-cache, -query-string-never-cache, -reset
 
 # shopt is necessary for this kind !(html|22222) of patterns
 shopt -s extglob
@@ -101,13 +101,10 @@ fi
 if [[ -n $subfolder && ! ( $subfolder =~ ^\/([A-Za-z0-9_\/\-]+)?[^\/]$ ) ]]; then
 	echo "${red}[ERROR] Please, enter a valid value for subfolder!${end}"
 	exit 1
-elif [[ -n $subfolder && -z $delete && -z $cache && -z $yoast_sitemap && -z $multisite_convert && -z $clone_from && -z $replace_content && -z $wp && -z $html && -z $php && -z $mysql && -z $proxy && -z $env ]]; then
+elif [[ -n $subfolder && -z $delete && -z $cache && -z $yoast_sitemap && -z $multisite_convert && -z $clone_from && -z $replace_content && -z $wp && -z $html && -z $php && -z $mysql && -z $proxy && -z $env && -z $info ]]; then
 	echo "${red}[ERROR] Subfolder option not supported!${end}"
 	exit 1
-elif [[ -n $subfolder && ( -n $cache || -n $yoast_sitemap || -n $multisite_convert || -n $replace_content ) && $(is_subfolder $domain $subfolder) != "wp" ]]; then
-	echo "${red}[ERROR] Subfolder not found or is not a WP site!${end}"
-	exit 1
-elif [[ -n $subfolder && -n $clone_from && $(is_subfolder $clone_from $subfolder) != "wp" ]]; then
+elif [[ -n $subfolder && ( $cache == "on" || -n $yoast_sitemap || -n $multisite_convert || -n $replace_content ) && $(is_subfolder $domain $subfolder) != "wp" ]]; then
 	echo "${red}[ERROR] Subfolder not found or is not a WP site!${end}"
 	exit 1
 else
@@ -128,12 +125,7 @@ if [[ -n $delete_all ]]; then
 # Create PHP or MySQL site
 elif [[ -n $mysql || ( -n $php && -n $domain ) ]]; then
 	if [[ -n $domain ]]; then
-		# Temporary FIX
-		if [[ $(is_proxy $domain) == "true" || ( -f /etc/nginx/sites-available/$domain && -n $(grep -F "proxy.conf;" /etc/nginx/sites-available/$domain)) ]]; then
-			echo "${red}[ERROR] Incompatible with your current Reverse-Proxy site! (We will fix this issue soon)${end}"
-			exit 1
-		fi
-		
+		full_empty_not_allowed
 		if [[ -f /etc/nginx/sites-available/$domain && -n $subfolder && $(is_subfolder $domain $subfolder) != "false" ]]; then
 			echo "${red}[ERROR] Subfolder${blu} $subfolder ${red}already exists!${end}"
 			exit 1
@@ -158,15 +150,16 @@ elif [[ -n $mysql || ( -n $php && -n $domain ) ]]; then
 	[[ -n $mysql ]] && wpinstall
 
 
+# Create EMPTY site
+elif [[ -n $empty && -n $domain ]]; then
+	full_empty_not_allowed
+	echo "${blu}You've created an EMPTY site, which means that you need to add your own NGINX configuration. ${dim}(/var/www/example.com/*-nginx.conf)${end}"
+	[[ $empty == "blank" ]] && create_empty_site -full || create_empty_site
+
+
 # Create HTML site
 elif [[ -n $html && -n $domain ]]; then
-	
-	# Temporary FIX
-	if [[ $(is_proxy $domain) == "true" || ( -f /etc/nginx/sites-available/$domain && -n $(grep -F "proxy.conf;" /etc/nginx/sites-available/$domain)) ]]; then
-		echo "${red}[ERROR] Incompatible with your current Reverse-Proxy site! (We will fix this issue soon)${end}"
-		exit 1
-	fi
-	
+	full_empty_not_allowed
 	if [[ -f /etc/nginx/sites-available/$domain && -n $subfolder && $(is_subfolder $domain $subfolder) != "false" ]]; then
 		echo "${red}[ERROR] Subfolder${blu} $subfolder ${red}already exists!${end}"
 		exit 1
@@ -190,12 +183,7 @@ elif [[ -n $html && -n $domain ]]; then
 
 # Create WP site
 elif [[ -n $wp && -n $domain ]]; then
-	# Temporary FIX
-	if [[ $(is_proxy $domain) == "true" || ( -f /etc/nginx/sites-available/$domain && -n $(grep -F "proxy.conf;" /etc/nginx/sites-available/$domain)) ]]; then
-		echo "${red}[ERROR] Incompatible with your current Reverse-Proxy site! (We will fix this issue soon)${end}"
-		exit 1
-	fi
-	
+	full_empty_not_allowed
 	if [[ -z $subfolder ]]; then
 		if [[ $(is_empty_root_site $domain) == "true" ]]; then		
 			wpinstall
@@ -250,26 +238,18 @@ elif [[ -n $multisite_convert && -f /etc/nginx/sites-available/$domain ]]; then
 
 # Parked Domain
 elif [[ -n $parked && -n $domain ]]; then
+	full_empty_not_allowed
 	parked_domain
 
 	
 # Reverse proxy
-elif [[ -n $proxy && -n $domain ]]; then
-	
-	# Temporary FIX
-	if [[ -n $subfolder && -f /etc/nginx/sites-available/$domain && $(is_proxy $domain) != "true" ]]; then
-		echo "${red}[ERROR] Reverse Proxy subfolders only can be installed when main site is reverse proxy! (We will fix this issue soon)${end}"
-		exit 1
-	elif [[ -z $subfolder && $(is_empty_root_site $domain) == "true" && -z $(grep -F "proxy.conf;" /etc/nginx/sites-available/$domain) ]]; then
-		echo "${red}[ERROR] Reverse-Proxy site incompatible with your current subfolders! (We will fix this issue soon)${end}"
-		exit 1
-	fi
-	
+elif [[ -n $proxy && -n $domain ]]; then	
 	reverse_proxy
 	
 
 # Forward domain
 elif [[ -n $forward && -n $domain ]]; then
+	full_empty_not_allowed
 	forward_domain
 	
 	
@@ -296,6 +276,11 @@ elif [[ -n $redirection && -f /etc/nginx/sites-available/$domain ]]; then
 	check_for_nginx
 	redirection_manager
 
+
+# FastCGI Cache
+elif [[ -n $cache && -f /etc/nginx/sites-available/$domain ]]; then
+	wp_cache
+
 	
 # Delete site	
 elif [[ -n $delete && -f /etc/nginx/sites-available/$domain ]]; then
@@ -319,6 +304,12 @@ elif [[ -n $delete && -f /etc/nginx/sites-available/$domain ]]; then
 		sudo sed -i "/# WebinolyCustom/,/# WebinolyCustomEnd/{/$domain$subname-proxy.conf/d}" /etc/nginx/sites-available/$domain
 		sudo sed -i "/# WebinolyNginxServerStart/,/# WebinolyNginxServerEnd/{\|location $subfolder/ |d}" /etc/nginx/sites-available/$domain
 		echo "${gre}Subfolder${blu} $subfolder ${gre}from${blu} $domain ${gre}has been successfully deleted!${end}"
+		
+		# In case of custom cache
+		if [[ -f /etc/nginx/conf.d/webinoly.conf ]]; then
+			sudo sed -i "/^fastcgi_cache_path \/run\/nginx-cache\/$(echo $domain | sed 's/[^0-9A-Za-z]/_/g')${subname} .*/d" /etc/nginx/conf.d/webinoly.conf
+			[[ ! -s /etc/nginx/conf.d/webinoly.conf ]] && sudo rm /etc/nginx/conf.d/webinoly.conf
+		fi
 	else
 		deletesite
 	fi
@@ -402,25 +393,27 @@ elif [[ -n $clone_from ]]; then
 	elif [[ -f /etc/nginx/sites-available/$domain && -n $subfolder && $(is_subfolder $domain $subfolder) != "false" && $overwrite != "on" ]]; then
 		echo "${red}[ERROR] Subfolder ${blu}'$subfolder'${red} already exists!${end}"
 		exit 1
-	elif [[ $(is_wp $clone_from $subfolder) != "true" ]]; then
-		echo "${red}[ERROR] Site${blu} ${clone_from}${subfolder} ${red}is not a WordPress site!${end}"
-		exit 1
 	elif [[ $(is_parked $clone_from) == "true" ]]; then
 		echo "${red}[ERROR] Cloning a parked site is not allowed!${end}"
 		exit 1
 	fi
 	
-	wp_conf_retrieve $clone_from $subfolder #We need to call this function in the parent shell to preserve variables and avoid asking two times for the same values in case of external db.
-	if [[ ( $wp_dbhost == "localhost" && $(check_mysql_connection localhost) != "true" ) || ( $wp_dbhost != "localhost" && $(check_mysql_connection $extdb_url $extdb_port $extdb_user $extdb_pass) != "true" ) ]]; then
-		exit 1
+	if [[ $(is_wp $clone_from $subfolder) == "true" ]]; then
+		#We need to call this function in the parent shell to preserve variables and avoid asking two times for the same values in case of external db.
+		wp_conf_retrieve $clone_from $subfolder 
+		iswpclone="true"
+		
+		if [[ ( $wp_dbhost == "localhost" && $(check_mysql_connection localhost) != "true" ) || ( $wp_dbhost != "localhost" && $(check_mysql_connection $extdb_url $extdb_port $extdb_user $extdb_pass) != "true" ) ]]; then
+			exit 1
+		elif [[ $(is_wp_multisite $clone_from $subfolder) != "false" ]]; then
+			echo "${red}[ERROR] WordPress Multisite can not be cloned!${end}"
+			exit 1
+		elif [[ $(is_wp_installed $clone_from $subfolder) != "true" ]]; then
+			echo "${dim}[INFO] WordPress is empty and still not configured in ${clone_from}${subfolder} site!${end}"
+		fi
 	fi
 	
-	if [[ $(is_wp_multisite $clone_from $subfolder) != "false" ]]; then
-		echo "${red}[ERROR] WordPress Multisite can not be cloned!${end}"
-		exit 1
-	else
-		clone_wp_site
-	fi
+	cloning_site
 
 
 # Replace Content
@@ -442,11 +435,6 @@ elif [[ -n $env && -f /etc/nginx/sites-available/$domain ]]; then
 	nginx_not="true" # Nginx-Reload not-needed.
 	
 
-# FastCGI Cache
-elif [[ -n $cache ]]; then
-	wp_cache
-	
-
 # List Sites
 elif [[ -n $list && -z $redirection ]]; then
 	list_sites
@@ -455,7 +443,7 @@ elif [[ -n $list && -z $redirection ]]; then
 
 # Site Info
 elif [[ -n $info && -f /etc/nginx/sites-available/$domain ]]; then
-	site_info
+	[[ -n $subfolder ]] && site_info_subfolder || site_info
 	nginx_not="true" # Nginx-Reload not-needed.
 	
 
