Update to Webinoly 1.16.1

diff --git a/assets/webinoly/usr/log b/assets/webinoly/usr/log
--- a/assets/webinoly/usr/log
+++ b/assets/webinoly/usr/log
@@ -17,20 +17,6 @@ error() {
 waiting_for_log() {
 	echo "${blu}[Log File is Empty] ${dim}Waiting to receive some data, you will see it in real-time here...${end}"
 }
-cnf_delete() {
-	#Example: cnf_delete error_log
-	[[ -f /etc/mysql/mariadb.conf.d/90-webinoly.cnf ]] && sudo sed -i "/^$1 /d" /etc/mysql/mariadb.conf.d/90-webinoly.cnf
-}
-cnf_write() {
-	#Example: cnf_write error_log /var/log/mysql/error.log
-	cnf_delete $1
-	[[ -n $2 ]] && local value="= $2"
-	echo "$1 $value" >> /etc/mysql/mariadb.conf.d/90-webinoly.cnf
-}
-cnf_read() {
-	#Example: cnf_read error_log
-	echo $( grep -P "^$1 = " /etc/mysql/mariadb.conf.d/90-webinoly.cnf | cut -f 2 -d "=" -s | sed 's/ //g' )
-}
 
 
 # Check for custom "lines" value
@@ -124,11 +110,11 @@ elif [[ -n $mysql ]]; then
 		if [[ -n $enable ]]; then
 			cnf_write general_log 1
 			cnf_write general_log_file /var/log/mysql/mysql.log
-			sudo service mysql restart
+			sudo systemctl restart mysql
 			echo "${gre}MariaDB General log was successfully enabled!${end}"
 		elif [[ -n $disable ]]; then
 			cnf_write general_log 0
-			sudo service mysql restart
+			sudo systemctl restart mysql
 			echo "${gre}MariaDB General log was successfully disabled!${end}"
 		elif [[ -f /var/log/mysql/mysql.log && $(cnf_read general_log) == 1 ]]; then
 			[[ ! -s /var/log/mysql/mysql.log ]] && waiting_for_log
@@ -144,12 +130,22 @@ elif [[ -n $mysql ]]; then
 	# Slow Query Log
 	elif [[ $mysql == "slow" ]]; then
 		if [[ -n $enable ]]; then
+			# https://mariadb.com/kb/en/slow-query-log-overview/
+			if [[ -n $long_query_time && $long_query_time =~ ^[0-9]+$ && $long_query_time -gt 1 ]]; then
+				cnf_write long_query_time $long_query_time
+				echo "${gre}${dim}MySQL long query time set to ${long_query_time}s ${end}"
+			elif [[ -n $long_query_time ]]; then
+				echo "${red}[ERROR] Invalid value for long query time! ${dim}(Should be a number greater than zero)${end}"
+				exit 1
+			fi
+			
 			cnf_write slow_query_log 1
-			sudo service mysql restart
+			sudo systemctl restart mysql
 			echo "${gre}MariaDB Slow Query log was successfully enabled!${end}"
 		elif [[ -n $disable ]]; then
+			# Don't remove long_query_time variable to preserve the value
 			cnf_write slow_query_log 0
-			sudo service mysql restart
+			sudo systemctl restart mysql
 			echo "${gre}MariaDB Slow Query log was successfully disabled!${end}"
 		elif [[ -f /var/log/mysql/mariadb-slow.log && $(cnf_read slow_query_log) == 1 ]]; then
 			[[ ! -s /var/log/mysql/mariadb-slow.log ]] && waiting_for_log
@@ -168,13 +164,13 @@ elif [[ -n $mysql ]]; then
 			cnf_delete skip-log-bin
 			cnf_write log_bin /var/log/mysql/mariadb-bin
 			cnf_write log_bin_index /var/log/mysql/mariadb-bin.index
-			sudo service mysql restart
+			sudo systemctl restart mysql
 			echo "${gre}MariaDB Binary log was successfully enabled!${end}"
 		elif [[ -n $disable ]]; then
 			cnf_delete log_bin
 			cnf_delete log_bin_index
 			cnf_write skip-log-bin
-			sudo service mysql restart
+			sudo systemctl restart mysql
 			echo "${gre}MariaDB Binary log was successfully disabled!${end}"
 		elif [[ -f /var/log/mysql/mariadb-bin && -n $(cnf_read log_bin) ]]; then
 			[[ ! -s /var/log/mysql/mariadb-bin ]] && waiting_for_log
@@ -229,7 +225,7 @@ elif [[ -n $only_error ]]; then
 			if [[ -z $islog ]]; then
 				[[ $(conf_read nginx) == "true" ]] && sudo sed -i '/access_log/c \	access_log off;' /etc/nginx/nginx.conf
 				conf_write global-access-log-off true
-				sudo service nginx reload
+				sudo systemctl reload nginx
 				echo "${gre}Only-Error Log was successfully enabled (global)!${end}"
 			else	
 				echo "${gre}Only-Error Log is already enabled (global)!${end}"
@@ -238,8 +234,8 @@ elif [[ -n $only_error ]]; then
 			api-events_update lg2
 			if [[ -n $islog || ( -z $islog && $(conf_read nginx) != "true" ) ]]; then
 				[[ $(conf_read nginx) == "true" ]] && sudo sed -i "/access_log/c \	access_log \/var\/log\/nginx\/access.log;" /etc/nginx/nginx.conf
-				conf_write global-access-log-off purged
-				sudo service nginx reload
+				conf_write global-access-log-off false
+				sudo systemctl reload nginx
 				echo "${gre}Only-Error Log was successfully disabled (global)!${end}"
 			else	
 				echo "${gre}Only-Error Log is already disabled (global)!${end}"
@@ -259,7 +255,7 @@ elif [[ -n $only_error ]]; then
 			api-events_update lg3
 			if [[ $(is_log $domain) == "true" ]]; then
 				sudo sed -i '/access_log/c \	access_log off;' /etc/nginx/sites-available/$domain
-				sudo service nginx reload
+				sudo systemctl reload nginx
 				echo "${gre}Only-Error Log was successfully enabled for ${blu}${domain} ${gre}site!${end}"
 			else	
 				echo "${gre}Access Log is already enabled for ${blu}${domain} ${gre}site!${end}"
@@ -268,7 +264,7 @@ elif [[ -n $only_error ]]; then
 			api-events_update lg4
 			if [[ $(is_log $domain) != "true" ]]; then
 				sudo sed -i "/access_log/c \	access_log \/var\/log\/nginx\/${domain}.access.log we_log;" /etc/nginx/sites-available/$domain
-				sudo service nginx reload
+				sudo systemctl reload nginx
 				echo "${gre}Only-Error Log was successfully disabled for ${blu}${domain} ${gre}site!${end}"
 			else	
 				echo "${gre}Access Log is already disabled for ${blu}${domain} ${gre}site!${end}"
@@ -289,10 +285,7 @@ elif [[ -n $domain && -f /etc/nginx/sites-available/$domain ]]; then
 	fi
 	
 	# WordPress Logs
-	if [[ -n $wp && $(is_parked $domain) == "true" ]]; then
-		echo "${red}[ERROR] Parked sites not allowed! ${dim}(WP debug should be used in main site)${end}"
-		exit 1
-	fi
+	[[ -n $wp && $(is_parked $domain) == "true" ]] && echo "${dim}[WARNING] WP Debug in a parked site will have effect over all your multisite network!${end}"
 	
 	if [[ -n $wp && $(is_wp $domain $subfolder) == "true" ]]; then
 		iswpdeb=$( is_wp_debug $domain $subfolder )
diff --git a/assets/webinoly/usr/site b/assets/webinoly/usr/site
--- a/assets/webinoly/usr/site
+++ b/assets/webinoly/usr/site
@@ -2,10 +2,10 @@
 
 # Site Manager Plugin (Create, delete and de/activate)
 # Syntax: site <domain> <option> <argument>
-# Options: -html, -php, -mysql, -wp, -parked, -proxy, -empty, -on, -off, -delete, -delete-all, -list, -cache, -ssl, -force-redirect, -yoast-sitemap, -multisite-convert, -clone-from, -replace-content, -redirection, -forward, -info, -env
-# Arguments: -cache, -root, -root-path, -subdomain, -ignore-ssl, -wildcard, -raw, -external-db, -revoke, -ssl-crt, -ssl-key, -ssl-ocsp, -subfolder, -from, -to, -http-code, -regex, -manual, -overwrite, -wp-cache-plugins, -dedicated-reverse-proxy, -must-staple, -cache-valid, -skip-cache, -skip-cookie-cache, -query-string-cache, -query-string-never-cache, -query-string-cache-default, -reset
+# Options: -html, -php, -mysql, -wp, -parked, -proxy, -empty, -on, -off, -delete, -delete-all, -list, -cache, -ssl, -force-redirect, -multisite-convert, -clone-from, -replace-content, -redirection, -forward, -info, -env
+# Arguments: -cache, -root, -root-path, -subdomain, -ignore-ssl, -wildcard, -raw, -external-db, -revoke, -ssl-crt, -ssl-key, -ssl-ocsp, -subfolder, -from, -to, -http-code, -regex, -manual, -overwrite, -wp-cache-plugins, -dedicated-reverse-proxy, -must-staple, -cache-valid, -skip-cache, -skip-cookie-cache, -query-string-cache, -query-string-never-cache, -query-string-cache-default, -reset, -test-cert, -db-role, -domain-mapping-wp-id
 
-# shopt is necessary for this kind !(html|22222) of patterns
+# shopt is necessary for this kind !(html|<toolsport>) of patterns
 shopt -s extglob
 
 source /opt/webinoly/lib/general
@@ -26,7 +26,7 @@ if [[ -n $wp || -n $mysql ]]; then
 
 	# Check for saved DB external data
 	if [[ ( $wp == "true" || $mysql == "true" ) && -n $(conf_read external-dbh) && -n $(conf_read external-dbu) && -n $(conf_read external-dbp) ]]; then
-		dona=$(echo $domain | sed "s/[^0-9A-Za-z]/_/g")
+		[[ -n $domain ]] && dona=$(echo $domain | sed "s/[^0-9A-Za-z]/_/g") || dona="Webinoly_$(pwgen -s -1)"
 		
 		if [[ -n $(conf_read external-dbh) && -n $(conf_read external-dbx) ]]; then
 			exth="$(conf_read external-dbh):$(conf_read external-dbx)"
@@ -35,8 +35,8 @@ if [[ -n $wp || -n $mysql ]]; then
 		fi
 		
 		extp=$( echo $(conf_read external-dbp) | openssl enc -d -a -salt )
-		[[ $wp == "true" ]] && wp=[true,true,$exth,$dona,$dona,random,wp_,$(conf_read external-dbu),$extp]
-		[[ $mysql == "true" ]] && mysql=[$exth,$dona,$dona,random,$(conf_read external-dbu),$extp]
+		[[ $wp == "true" ]] && wp="[true,true,${exth},${dona},${dona},random,wp_,$(conf_read external-dbu),${extp}]"
+		[[ $mysql == "true" ]] && mysql="[${exth},${dona},${dona},random,$(conf_read external-dbu),${extp}]"
 		echo "${blu}${dim}External DB credentials found!${end}"
 	fi
 
@@ -101,10 +101,10 @@ fi
 if [[ -n $subfolder && ! ( $subfolder =~ ^\/([A-Za-z0-9_\/\-]+)?[^\/]$ ) ]]; then
 	echo "${red}[ERROR] Please, enter a valid value for subfolder!${end}"
 	exit 1
-elif [[ -n $subfolder && -z $delete && -z $cache && -z $yoast_sitemap && -z $multisite_convert && -z $clone_from && -z $replace_content && -z $wp && -z $html && -z $php && -z $mysql && -z $proxy && -z $env && -z $info ]]; then
+elif [[ -n $subfolder && -z $delete && -z $cache && -z $multisite_convert && -z $clone_from && -z $replace_content && -z $wp && -z $html && -z $php && -z $mysql && -z $proxy && -z $env && -z $info ]]; then
 	echo "${red}[ERROR] Subfolder option not supported!${end}"
 	exit 1
-elif [[ -n $subfolder && ( $cache == "on" || -n $yoast_sitemap || -n $multisite_convert || -n $replace_content ) && $(is_subfolder $domain $subfolder) != "wp" ]]; then
+elif [[ -n $subfolder && ( $cache == "on" || -n $multisite_convert || -n $replace_content ) && $(is_subfolder $domain $subfolder) != "wp" ]]; then
 	echo "${red}[ERROR] Subfolder not found or is not a WP site!${end}"
 	exit 1
 else
@@ -194,7 +194,6 @@ elif [[ -n $wp && -n $domain ]]; then
 		fi
 		sudo sed -i '/locations.conf/i \	include common/wpcommon.conf;' /etc/nginx/sites-available/$domain
 		[[ $(conf_read wp-admin-auth) == "purged" ]] && sudo httpauth $domain -wp-admin=off > /dev/null 2>&1
-		[[ $(conf_read yoast-sitemap) == "true" ]] && sudo site $domain -yoast-sitemap=on > /dev/null 2>&1
 		[[ -n $env ]] && sudo site $domain -env=$env
 	else
 		if [[ -f /etc/nginx/sites-available/$domain && -n $subfolder && $type == [123] && $(is_subfolder $domain $subfolder) != "false" ]]; then
@@ -289,27 +288,7 @@ elif [[ -n $delete && -f /etc/nginx/sites-available/$domain ]]; then
 		echo "${red}[ERROR] System sites can not be removed!${end}"
 		exit 1
 	elif [[ -n $subfolder ]]; then
-		if [[ $(is_subfolder $domain $subfolder) == "false" ]]; then
-			echo "${red}[ERROR] Subfolder site not found!${end}"
-			exit 1
-		elif [[ -f /var/www/$domain/htdocs$subfolder/wp-config.php && $delete != "keep-db" ]]; then
-			db_delete $domain
-		fi
-		
-		sudo rm -rf /var/www/$domain/htdocs$subfolder
-		sudo rm -rf /etc/nginx/apps.d/$domain$subname-*.conf
-		sudo sed -i "/# WebinolyCustom/,/# WebinolyCustomEnd/{/$domain$subname-php.conf/d}" /etc/nginx/sites-available/$domain
-		sudo sed -i "/# WebinolyCustom/,/# WebinolyCustomEnd/{/$domain$subname-phpx.conf/d}" /etc/nginx/sites-available/$domain
-		sudo sed -i "/# WebinolyCustom/,/# WebinolyCustomEnd/{/$domain$subname-wpfc.conf/d}" /etc/nginx/sites-available/$domain
-		sudo sed -i "/# WebinolyCustom/,/# WebinolyCustomEnd/{/$domain$subname-proxy.conf/d}" /etc/nginx/sites-available/$domain
-		sudo sed -i "/# WebinolyNginxServerStart/,/# WebinolyNginxServerEnd/{\|location $subfolder/ |d}" /etc/nginx/sites-available/$domain
-		echo "${gre}Subfolder${blu} $subfolder ${gre}from${blu} $domain ${gre}has been successfully deleted!${end}"
-		
-		# In case of custom cache
-		if [[ -f /etc/nginx/conf.d/webinoly.conf ]]; then
-			sudo sed -i "/^fastcgi_cache_path \/run\/nginx-cache\/$(echo $domain | sed 's/[^0-9A-Za-z]/_/g')${subname} .*/d" /etc/nginx/conf.d/webinoly.conf
-			[[ ! -s /etc/nginx/conf.d/webinoly.conf ]] && sudo rm /etc/nginx/conf.d/webinoly.conf
-		fi
+		deletesite_subfolder
 	else
 		deletesite
 	fi
@@ -317,9 +296,14 @@ elif [[ -n $delete && -f /etc/nginx/sites-available/$domain ]]; then
 
 # SSL (Letsencrypt)
 elif [[ -n $ssl ]]; then
-	if [[ $ssl =~ ^(renew|force-renewal-all)$ && -z $domain ]]; then
+	if [[ $ssl == "renew" && -z $domain ]]; then
 			# Post-Hook removed because we always restart nginx at the end of site command
-			[[ $ssl == "renew" ]] && sudo certbot renew || sudo certbot renew --force-renewal
+			sudo certbot renew
+	elif [[ $ssl == "force-renewal-all" && -z $domain ]]; then
+			sudo certbot renew --force-renewal
+	elif [[ $ssl == "force-renewal" && -z $manual && -z $wildcard && -f /etc/nginx/sites-available/$domain && -f /etc/letsencrypt/live/$domain/fullchain.pem ]]; then
+			# Normal certs (not-manual) can be renewed easily using this way!
+			sudo certbot renew --cert-name $domain --force-renewal
 	elif [[ ( $ssl == "on" || $ssl == "force-renewal" ) && -f /etc/nginx/sites-available/$domain ]]; then
 		api-events_update si10
 		if [[ $(is_ssl $domain) == "true" && $ssl != "force-renewal" ]]; then
@@ -380,11 +364,6 @@ elif [[ -n $force_redirect && -f /etc/nginx/sites-available/$domain ]]; then
 	force_redirect
 
 
-# Yoast Sitemap support, per site.
-elif [[ -n $yoast_sitemap && -f /etc/nginx/sites-available/$domain ]]; then
-	yoast_sitemap
-
-
 # Staging and Clone sites
 elif [[ -n $clone_from ]]; then
 	if [[ ! -f /etc/nginx/sites-available/$clone_from ]]; then
@@ -403,10 +382,13 @@ elif [[ -n $clone_from ]]; then
 	
 	if [[ $(is_wp $clone_from $subfolder) == "true" ]]; then
 		#We need to call this function in the parent shell to preserve variables and avoid asking two times for the same values in case of external db.
-		wp_conf_retrieve $clone_from $subfolder 
+		wp_conf_retrieve $clone_from true false $subfolder 
 		iswpclone="true"
 		
-		if [[ ( $wp_dbhost == "localhost" && $(check_mysql_connection localhost) != "true" ) || ( $wp_dbhost != "localhost" && $(check_mysql_connection $extdb_url $extdb_port $extdb_user $extdb_pass) != "true" ) ]]; then
+		if [[ -z $wp_dbhost || -z $wp_dbname || -z $wp_dbpref ]]; then
+			echo "${red}[ERROR] Can not retrieve WP data ${dim}(WP Configuration corrupted)!${end}"
+			exit 1
+		elif [[ ( $wp_dbhost == "localhost" && $(check_mysql_connection localhost) != "true" ) || ( $wp_dbhost != "localhost" && $(check_mysql_connection $extdb_url $extdb_port $extdb_user $extdb_pass) != "true" ) ]]; then
 			exit 1
 		elif [[ $(is_wp_multisite $clone_from $subfolder) != "false" ]]; then
 			echo "${red}[ERROR] WordPress Multisite can not be cloned!${end}"
@@ -423,9 +405,6 @@ elif [[ -n $clone_from ]]; then
 elif [[ -n $replace_content && -f /etc/nginx/sites-available/$domain ]]; then
 	if [[ $(is_wp $domain $subfolder) != "true" ]]; then
 		echo "${red}[ERROR] Site${blu} $domain$subfolder ${red}is not a WordPress site!${end}"
-		exit 1
-	elif [[ $(is_parked $domain) == "true" ]]; then
-		echo "${red}[ERROR] Parked sites are not allowed for replace-content!${end}"
 		exit 1
 	else
 		wp_replace_content
@@ -468,5 +447,5 @@ else
 fi
 
 shopt -u extglob
-[[ $(conf_read nginx) == "true" && -z $nginx_not && $(conf_read nginx-reload) != "false" ]] && sudo service nginx reload
+[[ $(conf_read nginx) == "true" && -z $nginx_not && $(conf_read nginx-reload) != "false" ]] && sudo systemctl reload nginx
 api-events_update sie
diff --git a/assets/webinoly/weby b/assets/webinoly/weby
--- a/assets/webinoly/weby
+++ b/assets/webinoly/weby
@@ -13,6 +13,13 @@ if ! [[ $distr == "Ubuntu" && $osver =~ ^(bionic|focal)$ ]]; then
 	read -p "Press [Enter] key to Continue or [Ctrl+C] to Cancel..."
 fi
 
+# Check for BASH Shell
+if [[ -z $(grep -E "^${SUDO_USER:-${USER}}\:.*\/bash.*$" /etc/passwd) ]]; then
+	echo "$(tput setaf 1)BASH Shell is required!$(tput sgr0)"
+	sudo rm weby
+	exit 1
+fi
+
 # Check for sudo/root privileges
 if [[ $(whoami) != "root" ]]; then
 	echo "$(tput setaf 1)Please run this script as root or using sudo.$(tput sgr0)"
@@ -23,7 +30,7 @@ fi
 # Prevent "compulsive" re-installation, force the use of the 'update' command.
 if [[ -f /opt/webinoly/webinoly.conf && $1 != "upd" && $2 != "-ver=alpha" ]]; then
 	echo "$(tput setaf 2)Webinoly is already installed on your server!"
-	echo "$(tput setaf 6)To update use the proper command.$(tput sgr0)"
+	echo "$(tput setaf 6)To update use the proper command:$(tput dim) sudo webinoly -update $(tput sgr0)"
 	sudo rm weby
 	exit 0
 elif [[ ! -f /opt/webinoly/webinoly.conf && $1 == "upd" ]]; then
@@ -36,16 +43,27 @@ fi
 if [[ $1 == "upd" ]]; then
 	setup=0
 	update="&update=true"
+elif [[ $1 == "-clean" ]]; then
+	setup=0
+elif [[ $1 == "-nginx" ]]; then
+	setup=1
+elif [[ $1 == "-php" ]]; then
+	setup=2
+elif [[ $1 == "-lemp" ]]; then
+	setup=3
+elif [[ -z $1 ]]; then
+	setup=3
 elif ! [[ $1 -ge 0 && $1 -le 3 && $1 =~ ^[0-9]+$ ]]; then
 	echo "$(tput setaf 6)"
 	echo "  1 - HTML Server"
 	echo "  2 - PHP Server"
 	echo "  3 - LEMP Server (Default)"
-	echo "  0 - Maybe later..."
+	echo "  0 - Clean (Only app)"
 	echo ""
 	read -p "$(tput setaf 2)Select the desired option to configure your server: $(tput sgr0)" setup
 	echo ""
 	setup=${setup:-3}
+	[[ $setup -ge 0 && $setup -le 3 && $setup =~ ^[0-9]+$ ]] || setup=0
 else
 	setup=$1
 fi
@@ -92,8 +110,11 @@ sudo find /opt/webinoly -type d -exec chmod 755 {} \;
 sudo find /opt/webinoly -type f -exec chmod 644 {} \;
 sudo chmod -f 744 /opt/webinoly/lib/ex-*
 
-sudo chmod 755 /opt/webinoly/plugins/*
-sudo mv /opt/webinoly/plugins/* /usr/bin/
+# REMOVE when unsupported! (Only to maintain compatibility with versions before 1.16.0)
+[[ ! -d /opt/webinoly/usr ]] && usrw="/opt/webinoly/plugins" || usrw="/opt/webinoly/usr"
+
+sudo chmod 755 ${usrw}/*
+sudo mv ${usrw}/* /usr/bin/
 
 source /opt/webinoly/lib/general
 
@@ -102,12 +123,7 @@ if [[ -f $HOME/.webinoly-conf-restore_dont-remove ]]; then
 	echo "${gre}Seems like Webinoly was installed previously, we will try to recover your old configuration!${end}"
 	sudo tar -Pxf $HOME/.webinoly-conf-restore_dont-remove -C /
 	sudo rm -rf $HOME/.webinoly-conf-restore_dont-remove
-	sudo webinoly -verify
-	if [[ $? != 0 ]]; then
-		sudo rm weby
-		app_purge
-		exit 1
-	fi
+	sudo webinoly -verify=critical
 fi
 
 
@@ -116,7 +132,7 @@ if [[ -f /opt/webinoly/webinoly.conf ]]; then
 	oldapp=$(conf_read app-version)
 	oldver=$(conf_read server-version)
 	newver=$svr_version
-	echo "${gre}Webinoly Configuration file was found, so we will use it!${end}"
+	echo "${gre}${dim}Webinoly Configuration file was found, so we will use it!${end}"
 else
 	new_install="true"
 fi
@@ -150,40 +166,60 @@ if [[ $statskip != "true" ]]; then
 		opt=$oldapp
 	else
 		type="Error"
-		echo "${red}[WARNING] Installation method not recognized!${end}"
+		echo "${red}[ERROR] Installation method not recognized!${end}"
 	fi
 
 	wget https://api.webinoly.com/stats/?install=${branch}:${webyversion}:${type}:${opt} --referer="Webinoly-Internal-Verified-Stats" --spider --timeout=15 -t 1 -q
 fi
 
 
-# Stack installation & updates
+# Update stack!
 [[ -n $oldver && ${newver//.} -gt ${oldver//.} ]] && source /opt/webinoly/lib/update
-[[ $setup -gt 0 && $setup -le 3 ]] && stack -nginx
-[[ $setup -gt 1 && $setup -le 3 ]] && stack -php
-[[ $setup == 3 ]] && stack -mysql
+[[ -f /usr/bin/duply && -f /opt/webinoly/templates/general/duply ]] && sudo cp /opt/webinoly/templates/general/duply /usr/bin/ && sudo chmod 755 /usr/bin/duply
 
+# Stack installation
+[[ $setup == 1 ]] && stack -nginx
+[[ $setup == 2 ]] && stack -php=nginx
+[[ $setup == 3 ]] && stack -lemp
+[[ $setup != [123] && -n $(conf_read stack-build-error-flag) ]] && sudo webinoly -verify=critical
 
 # Message Center
-if [[ $new_install == "true" && $setup == 0 ]]; then
-	echo "${blu}You have chosen the option '0', it means that you have to manually build your own stack."
-	echo "But, don't worry! With Webinoly this is an easy task, just use the stack command, i.e. 'sudo stack -lemp'"
-	echo "${gre}"
-	echo "Webinoly has been successfully installed!!!"
-fi
+if [[ -z $(conf_read stack-build-error-flag) ]]; then
+	if [[ $new_install == "true" && $setup == 0 ]]; then
+		echo "${blu}You have chosen the option '0', it means that you have to manually build your own stack."
+		echo "But, don't worry! With Webinoly this is an easy task, just use the stack command, i.e. 'sudo stack -lemp' ${end}"
+	fi
 
-echo "${blu}"
-echo "****************************************************************************"
-echo "************************${bol}     D O N A T I O N S     ${end}${blu}*************************"
-echo "***   ${dim}If you like Webinoly, buy me a coffee or a beer to show support.${end}${blu}   ***"
-echo "****************************************************************************"
-echo "*************     Bitcoin: 1E3Ybo5UcvaAr1MoK4nBnMRFFY9aEMiku3     **********"
-echo "*******   GitHub Sponsors: https://github.com/sponsors/QROkes     **********"
-echo "***************    PayPal: https://www.paypal.me/qrokes     ****************"
-echo "****************************************************************************"
-echo "***   ${dim}Your regular donations is what keep this project moving forward.${end}${blu}   ***"
-echo "****************************************************************************"
-echo "${end}"
+	if [[ -z $update ]]; then
+		echo ""
+		echo "${blu}${bol}Don't like our defaults? Every part of Webinoly is overrideable!${end}"
+		echo "${blu}- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - "
+		echo "${blu}Please, read the documentation:${end}${dim} https://webinoly.com/documentation/${end}"
+		echo "${blu}Be sure your firewall ports are correctly set:${end}${dim} https://webinoly.com/install/${end}"
+		echo "${blu}Configuration file is here:${end}${dim} /opt/webinoly/webinoly.conf${end}"
+		echo ""
+	fi
+	
+	[[ $setup == 0 ]] && echo "${gre}${dim}Webinoly has been successfully installed!!!${end}"
+	[[ $setup == 1 ]] && echo "${gre}${dim}Nginx and some other useful tools have been installed successfully! ${end}"
+	[[ $setup == 2 ]] && echo "${gre}${dim}Nginx, PHP and some other useful tools have been installed successfully! ${end}"
+	[[ $setup == 3 ]] && echo "${gre}${dim}Nginx, PHP, MySQL (MariaDB) and some other useful tools have been installed successfully! ${end}"
+	
+	echo "${blu}"
+	echo "****************************************************************************"
+	echo "************************     D O N A T I O N S     *************************"
+	echo "***    ${bol}If you like Webinoly, buy me a coffee or beer to show support.${end}${blu}    ***"
+	echo "****************************************************************************"
+	echo "*************     Bitcoin: ${end}${dim}1E3Ybo5UcvaAr1MoK4nBnMRFFY9aEMiku3     ${end}${blu}**********"
+	echo "*******   GitHub Sponsors:${end}${dim} https://github.com/sponsors/QROkes     ${end}${blu}**********"
+	echo "***************    PayPal:${end}${dim} https://www.paypal.me/qrokes     ${end}${blu}****************"
+	echo "****************************************************************************"
+	echo "***   ${end}${dim}Your regular donations is what keep this project moving forward.${end}${blu}   ***"
+	echo "****************************************************************************"
+	echo "${end}"
+else
+	echo "${red}[ERROR] Sorry, unexpected error during installation and building stack process!${end}"
+fi
 
 
 # Remove Installation File
