Update to Webinoly 1.17.4

diff --git a/assets/webinoly/usr/site b/assets/webinoly/usr/site
--- a/assets/webinoly/usr/site
+++ b/assets/webinoly/usr/site
@@ -104,7 +104,7 @@ elif [[ -n $subfolder && -z $delete && -z $cache && -z $multisite_convert && -z 
 	echo "${red}[ERROR] Subfolder option not supported!${end}"
 	exit 1
 # Clone-from empty is here to allow -cache=on when cloning a site
-elif [[ -n $subfolder && ( $cache == "on" || -n $multisite_convert || -n $replace_content ) && $(is_subfolder $domain $subfolder) != "wp" && -z $clone_from ]]; then
+elif [[ -n $subfolder && -z $wp && ( $cache == "on" || -n $multisite_convert || -n $replace_content ) && $(is_subfolder $domain $subfolder) != "wp" && -z $clone_from ]]; then
 	echo "${red}[ERROR] Subfolder not found or is not a WP site!${end}"
 	exit 1
 else
@@ -217,9 +217,7 @@ elif [[ -n $multisite_convert && -f /etc/nginx/sites-available/$domain ]]; then
 		exit 1
 	fi
 	
-	# We need to call this function in the parent shell to preserve variables and avoid asking two or more times for the same values in case of external db.
-	wp_conf_retrieve $domain true false $subfolder 	
-	
+	wp_conf_retrieve $domain false false $subfolder
 	if [[ $(is_wp_installed $domain $subfolder) != "true" ]]; then
 		echo "${red}[ERROR] WordPress site${blu} $domain$subfolder ${red}is empty and still not configured!${end}"
 		exit 1
@@ -371,14 +369,14 @@ elif [[ -n $clone_from ]]; then
 	fi
 	
 	if [[ $(is_wp $clone_from $subfolder) == "true" ]]; then
-		#We need to call this function in the parent shell to preserve variables and avoid asking two times for the same values in case of external db.
-		wp_conf_retrieve $clone_from true false $subfolder 
+		wp_conf_retrieve $clone_from true false $subfolder
 		iswpclone="true"
 		
-		if [[ -z $wp_dbhost || -z $wp_dbname || -z $wp_dbpref ]]; then
+		if [[ -z $wp_dbhost ||-z $wp_dbhost_host || -z $wp_dbname || -z $wp_dbpref ]]; then
 			echo "${red}[ERROR] Can not retrieve WP data ${dim}(WP Configuration corrupted)!${end}"
 			exit 1
-		elif [[ ( $wp_dbhost == "localhost" && $(check_mysql_connection localhost) != "true" ) || ( $wp_dbhost != "localhost" && $(check_mysql_connection $extdb_url $extdb_port $extdb_user $extdb_pass) != "true" ) ]]; then
+		elif [[ ( $wp_dbhost_host == "localhost" && $(check_mysql_connection localhost $mysql_param) != "true" ) || ( $wp_dbhost_host != "localhost" && $(check_mysql_connection $wp_dbhost_host $wp_dbhost_port any -login-file -master-admin) != "true" ) ]]; then
+			echo "${red}[ERROR] Database connection failed! ${dim}($wp_dbhost)${end}"
 			exit 1
 		elif [[ $(is_wp_multisite $clone_from $subfolder) != "false" ]]; then
 			echo "${red}[ERROR] WordPress Multisite can not be cloned!${end}"
@@ -401,15 +399,7 @@ elif [[ -n $replace_content && -f /etc/nginx/sites-available/$domain ]]; then
 		exit 1
 	fi
 	
-	#We need to call this function in the parent shell to preserve variables and avoid asking two times for the same values in case of external db.
-	wp_conf_retrieve $domain true true $subfolder
-	
-	if [[ $(is_wp_installed $domain $subfolder) != "true" ]]; then
-		echo "${red}[ERROR] WordPress is empty and still not configured in ${domain}${subfolder} site!${end}"
-		exit 1
-	else
-		wp_replace_content
-	fi
+	wp_replace_content
 
 
 # WordPress Environment Type (should be here after cloning site for precedence)
@@ -427,7 +417,7 @@ elif [[ -n $cache && -f /etc/nginx/sites-available/$domain ]]; then
 # Delete site (should be here after cache for precedence)
 elif [[ -n $delete && -f /etc/nginx/sites-available/$domain ]]; then
 	api-events_update si6
-	if [[ $domain == "default" || $domain == $(conf_read tools-port) ]]; then
+	if [[ $domain == "default" || $domain == $ADMIN_TOOLS_SITE ]]; then
 		echo "${red}[ERROR] System sites can not be removed!${end}"
 		exit 1
 	elif [[ -n $subfolder ]]; then
@@ -468,4 +458,5 @@ fi
 
 shopt -u extglob
 [[ $(conf_read nginx) == "true" && -z $nginx_not && $(conf_read nginx-reload) != "false" ]] && sudo systemctl reload nginx
+
 api-events_update sie
diff --git a/assets/webinoly/usr/webinoly b/assets/webinoly/usr/webinoly
--- a/assets/webinoly/usr/webinoly
+++ b/assets/webinoly/usr/webinoly
@@ -12,7 +12,6 @@ source /opt/webinoly/lib/bkp
 check_for_parameters $@
 api-events_update wys
 
-
 if [[ -n $update ]]; then
 	api-events_update wy1
 	webinoly_update
@@ -42,7 +41,7 @@ elif [[ -n $server_reset ]]; then
 	api-events_update wy2
 	if [[ $server_reset == true ]]; then
 		server_reset="all"
-	elif ! [[ $server_reset =~ ^(all|nginx|php|mysql|permissions)$ ]]; then
+	elif ! [[ $server_reset =~ ^(all|os|nginx|php|mysql|permissions)$ ]]; then
 		echo "${red}[ERROR] Please, enter a valid option to update/reset your server configuration!${end}"
 		exit 1
 	fi
@@ -84,7 +83,8 @@ elif [[ -n $uninstall ]]; then
 	api-events_update wy4
 	webinoly_uninstall
 	nginx_not="true" # Nginx-Reload not-needed.
-
+	ads_block="true" # Don't show ads
+	
 	
 elif [[ -n $external_sources_update ]]; then
 	external_sources_update
@@ -111,8 +111,15 @@ elif [[ -n $timezone ]]; then
 		read -p "${blu}Timezone: ${end}" timezone
 		echo ""
 	fi
-	conf_write timezone $timezone
-	set_timezone
+	
+	# Check first here to not overwrite a valid good value with a wrong value.
+	if [[ -n $timezone ]] && grep -Fxq $timezone /opt/webinoly/lib/timezone.dat; then
+		conf_write timezone $timezone
+		set_timezone
+	else
+		echo "${red}Timezone not found or not valid!${end}"
+		exit 1
+	fi
 	nginx_not="true" # Nginx-Reload not-needed.
 	
 
@@ -156,7 +163,7 @@ elif [[ -n $default_site ]]; then
 	
 elif [[ -n $mysql_password ]]; then
 	if [[ $(conf_read mysql) != "true" ]]; then
-		echo "${red}[ERROR] Seems like MySQL is not installed!${end}"
+		echo "${red}[ERROR] Seems like MySQL/MariaDB is not installed!${end}"
 		exit 1
 	elif [[ $(check_mysql_connection localhost) != "true" ]]; then
 		exit 1
@@ -282,6 +289,10 @@ elif [[ -n $custom_headers ]]; then
 elif [[ -n $query_string_cache || -n $query_string_never_cache || -n $skip_cache || -n $skip_cookie_cache ]]; then
 	check_for_nginx
 	custom_cache_global
+elif [[ -n $query_string_cache_default ]]; then
+	echo "${red}[ERROR] This option (-query-string-cache-default) is only enabled for specific sites using Custom Cache!"
+	echo "${blu}${dim}The option you are looking for is only available in the Webinoly configuration file. (wpcache-query-strings)${end}"
+	exit 1
 
 
 elif [[ -n $email ]]; then
diff --git a/assets/webinoly/weby b/assets/webinoly/weby
--- a/assets/webinoly/weby
+++ b/assets/webinoly/weby
@@ -4,9 +4,52 @@
 # Check OS support
 distr=`echo $(lsb_release -i | cut -d':' -f 2)`
 osver=`echo $(lsb_release -c | cut -d':' -f 2)`
-if ! [[ $distr == "Ubuntu" && $osver =~ ^(bionic|focal|jammy)$ ]]; then
+
+# Check for custom version
+if [[ $2 == "-ver="* ]]; then
+	ver=$(echo "$2" | cut -d'=' -f 2 -s)
+	# Skip stadistics counters for dev and testing (custom version stats).
+	if [[ $(echo $ver | rev | cut -c-1) == "*" || $ver == "alpha" ]]; then
+		ver=${ver//'*'}
+		statskip="true"
+	fi
+fi
+
+# Supported: 22.04 Jammy and 20.04 Focal
+if [[ $distr != "Ubuntu" ]] || ! [[ $osver =~ ^(bionic|focal|jammy)$ ]]; then
 	echo "$(tput setaf 1)"
 	echo "[ERROR] This OS is not supported by Webinoly and could not work properly. $(tput dim)(${distr} '${osver}')"
+	echo "$(tput sgr0)"
+	sudo rm weby
+	exit 1
+
+# 18.04 Bionic can be installed before 1.17.0
+elif [[ $osver == "bionic" && $1 != "upd" && -n $ver && $(echo ${ver//'*'} | sed 's/\.//g') =~ ^[0-9]+$ && $(echo ${ver//'*'} | sed 's/\.//g') -ge 1170 ]]; then
+	echo "$(tput setaf 1)"
+	echo "[ERROR] Ubuntu 18.04 is not supported on this version of Webinoly!"
+	echo "$(tput sgr0)"
+	sudo rm weby
+	exit 1
+elif [[ $osver == "bionic" && $1 != "upd" && -n $ver && $(echo ${ver//'*'} | sed 's/\.//g') =~ ^[0-9]+$ && $(echo ${ver//'*'} | sed 's/\.//g') -lt 1170 ]]; then
+	echo "$(tput setaf 1)"
+	echo "[WARNING] You should consider a newer Ubuntu version! $(tput dim)(20.04 or 22.04 are recommended instead)"
+	echo "$(tput sgr0)"
+	
+# 18.04 Bionic just for updates, no new installations after 1.17.0
+elif [[ $osver == "bionic" && $1 != "upd" ]]; then
+	echo "$(tput setaf 1)"
+	echo "[ERROR] Ubuntu 18.04 is not supported for new installations! $(tput dim)(20.04 or 22.04 are recommended instead)"
+	echo "$(tput sgr0)"
+	sudo rm weby
+	exit 1
+
+# 22.04 Jammy is supported only after 1.16.6
+elif [[ $osver == "jammy" && -n $ver && $(echo ${ver//'*'} | sed 's/\.//g') =~ ^[0-9]+$ && $(echo ${ver//'*'} | sed 's/\.//g') -lt 1166 ]]; then
+	#jammy - 1.16.6
+	#focal - 1.12.0
+	#bionic - 1.4.2
+	echo "$(tput setaf 1)"
+	echo "[ERROR] Ubuntu 22.04 (Jammy) is not supported by this version!"
 	echo "$(tput sgr0)"
 	sudo rm weby
 	exit 1
@@ -62,14 +105,7 @@ fi
 
 
 # Download and install Webinoly
-if [[ $2 == "-ver="* ]]; then
-	ver=$(echo "$2" | cut -d'=' -f 2 -s)
-	# Skip stadistics counters for dev and testing (custom version stats).
-	if [[ $(echo $ver | rev | cut -c-1) == "*" || $ver == "alpha" ]]; then
-		ver=${ver//'*'}
-		statskip="true"
-	fi
-	
+if [[ -n $ver ]]; then
 	# Be sure we have a valid server response for the requested version
 	code=$(wget --server-response --spider https://qrok.es/webinoly?version=$ver 2>&1 | awk '/^  HTTP/{print $2}')
 	code="${code##*$'\n'}" # Get the last code (redirections)
@@ -101,12 +137,8 @@ sudo mkdir -p /opt/webinoly/templates/source
 sudo find /opt/webinoly -type d -exec chmod 755 {} \;
 sudo find /opt/webinoly -type f -exec chmod 644 {} \;
 sudo chmod -f 744 /opt/webinoly/lib/ex-*
-
-# REMOVE when unsupported! (Only to maintain compatibility with versions before 1.16.0)
-[[ ! -d /opt/webinoly/usr ]] && usrw="/opt/webinoly/plugins" || usrw="/opt/webinoly/usr"
-
-sudo chmod 755 ${usrw}/*
-sudo mv ${usrw}/* /usr/bin/
+sudo chmod 755 /opt/webinoly/usr/*
+sudo mv /opt/webinoly/usr/* /usr/bin/
 
 source /opt/webinoly/lib/general
 
@@ -137,32 +169,33 @@ conf_write app-version $webyversion
 
 
 # Ping to Webinoly Stats
-if [[ $statskip != "true" ]]; then
-	opt=$setup
-	branch="Public"
+# statskip="true"
+# if [[ $statskip != "true" ]]; then
+# 	opt=$setup
+# 	branch="Public"
 
-	if [[ $new_install == "true" ]]; then
-		type="New"
-	elif [[ $ver == "beta" ]]; then
-		type="Beta"
-	elif [[ -n $update && $ver =~ ^[0-9]{1}\.[0-9]{1,2}\.[0-9]{1,2}$ ]]; then
-		type="Downgrade"
-		webyversion=$(wget --timeout=10 -t 1 -qO- https://api.webinoly.com/check?text=true)
-		opt=$ver
-	elif [[ -n $setup && $ver =~ ^[0-9]{1}\.[0-9]{1,2}\.[0-9]{1,2}$ ]]; then
-		type="Custom"
-		webyversion=$(wget --timeout=10 -t 1 -qO- https://api.webinoly.com/check?text=true)
-		opt=$ver
-	elif [[ -n $update && -n $oldapp ]]; then
-		type="Updates"
-		opt=$oldapp
-	else
-		type="Error"
-		echo "${red}[ERROR] Installation method not recognized!${end}"
-	fi
+# 	if [[ $new_install == "true" ]]; then
+# 		type="New"
+# 	elif [[ $ver == "beta" ]]; then
+# 		type="Beta"
+# 	elif [[ -n $update && $ver =~ ^[0-9]{1}\.[0-9]{1,2}\.[0-9]{1,2}$ ]]; then
+# 		type="Downgrade"
+# 		webyversion=$(wget --timeout=10 -t 1 -qO- https://api.webinoly.com/check?text=true)
+# 		opt=$ver
+# 	elif [[ -n $setup && $ver =~ ^[0-9]{1}\.[0-9]{1,2}\.[0-9]{1,2}$ ]]; then
+# 		type="Custom"
+# 		webyversion=$(wget --timeout=10 -t 1 -qO- https://api.webinoly.com/check?text=true)
+# 		opt=$ver
+# 	elif [[ -n $update && -n $oldapp ]]; then
+# 		type="Updates"
+# 		opt=$oldapp
+# 	else
+# 		type="Error"
+# 		echo "${red}[ERROR] Installation method not recognized!${end}"
+# 	fi
 
-	wget https://api.webinoly.com/stats/?install=${branch}:${webyversion}:${type}:${opt} --referer="Webinoly-Internal-Verified-Stats" --spider --timeout=15 -t 1 -q
-fi
+# 	wget https://api.webinoly.com/stats/?install=${branch}:${webyversion}:${type}:${opt} --referer="Webinoly-Internal-Verified-Stats" --spider --timeout=15 -t 1 -q
+# fi
 
 
 # Update stack!
@@ -173,7 +206,13 @@ fi
 [[ $setup == 1 ]] && stack -nginx
 [[ $setup == 2 ]] && stack -php=nginx
 [[ $setup == 3 ]] && stack -lemp
-[[ $setup != [123] && -n $(conf_read stack-build-error-flag) ]] && sudo webinoly -verify=critical
+
+# Verify installation!
+if [[ $setup != [123] && -n $update && -n $oldapp ]]; then
+	sudo webinoly -verify=critical -check-for-updates
+elif [[ $setup != [123] ]]; then
+	sudo webinoly -verify=critical
+fi
 
 # Message Center
 if [[ -z $(conf_read stack-build-error-flag) ]]; then
@@ -196,19 +235,7 @@ if [[ -z $(conf_read stack-build-error-flag) ]]; then
 	[[ $setup == 1 ]] && echo "${gre}${dim}Nginx and some other useful tools have been installed successfully! ${end}"
 	[[ $setup == 2 ]] && echo "${gre}${dim}Nginx, PHP and some other useful tools have been installed successfully! ${end}"
 	[[ $setup == 3 ]] && echo "${gre}${dim}Nginx, PHP, MySQL (MariaDB) and some other useful tools have been installed successfully! ${end}"
-	
-	echo "${blu}"
-	echo "****************************************************************************"
-	echo "************************     D O N A T I O N S     *************************"
-	echo "***    ${bol}If you like Webinoly, buy me a coffee or beer to show support.${end}${blu}    ***"
-	echo "****************************************************************************"
-	echo "*************     Bitcoin: ${end}${dim}1E3Ybo5UcvaAr1MoK4nBnMRFFY9aEMiku3     ${end}${blu}**********"
-	echo "*******   GitHub Sponsors:${end}${dim} https://github.com/sponsors/QROkes     ${end}${blu}**********"
-	echo "***************    PayPal:${end}${dim} https://www.paypal.me/qrokes     ${end}${blu}****************"
-	echo "****************************************************************************"
-	echo "***   ${end}${dim}Your regular donations is what keep this project moving forward.${end}${blu}   ***"
-	echo "****************************************************************************"
-	echo "${end}"
+
 else
 	echo "${red}[ERROR] Sorry, unexpected error during installation and building stack process!${end}"
 fi
